### ISSUE TITLE
Create project logo

### ISSUE THREAD

**Issue by Kathleenfrancois** [hackforla/peopledepot#153]
### Overview
We need a People Depot logo for One Sheet, Wiki and project page.  

### Action Items
- [x] Create logo
  - [x] Once finalized, add link to the logo from figma in a new comment below and in PD Wiki design page
  - [ ] Release dependency on this issue in #154  and add a link to the logo from figma in a new comment within #154
  - [ ] Release dependency on this issue in #136 and add a link to the logo from figma in a new comment within #136 
  - [ ] Release the dependency on this issue in #139 and add a link to the logo from figma in a new comment within #139

### Resources/Instructions
- [onesheet](https://docs.google.com/document/d/1kYGSrrWvVWNM4_cHq_q2FU86BTNtZ6MTNM60IeSUyv4/edit)
- [People Depo WIKI, Design page](https://github.com/hackforla/peopledepot/wiki/Design)
- [people depot figma](https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=1-2&node-type=canvas&t=yV564Ai893HLuVvz-0)

**Comment by shmonks** [comment]
hii sara, I have added the doc here : https://drive.google.com/file/d/1SWluEBOeFfPkgoUQoPeCS3w-slNVhlHF/view?usp=drive_link

**Comment by shmonks** [comment]
This is the Google Drive folder for Design: https://drive.google.com/drive/folders/1dkJjxn_F5W6PxtXjseV3dNA9bh4AzS9W?usp=drive_link

**Comment by sonaliagle** [comment]
https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=1-2&t=dPDVZ95JP7jxDsFH-1

**Comment by sonaliagle** [comment]
notes : remove the background color to make the logo more visible. Maybe try different color combinations?

**Comment by shmonks** [comment]
Hi @sonaliagle - please consider the following questions and add an update below:
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures (if necessary): "Add any pictures that will help illustrate what you are working on."

**Comment by sonaliagle** [comment]
Hi @shmonks , here are the updates:

1. Progress: Logo is selected, we are yet to decide on a color. Once it is through, rest of the deliverables can be shared as a file.
2. Blockers: Once the background color is finalised, I need to know what rest is expected off me in terms of deliverables : email signature? letter head? presentation? 
3. Availability: I am available for around 20 hours or as needed next week. However, I won't be available from 17th Oct - 24th Oct as my dad is visiting me from India.
4. ETA: Completion of tasks depends on the feedbacks, quicker we get through it, the sooner it gets done.
5. Pictures (if necessary): adding the link to figma in the next message

**Comment by sonaliagle** [comment]
added the link : https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=1-2&t=Pa6rlNq1Y0t1P4dd-1

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by sonaliagle** [comment]
Progress: trying variations of the existing logo to see if its adaptable  
Blockers: Once the favicon is finalised, I need to know what rest is expected off me in terms of deliverables : email signature? letter head? presentation?
Availability: I am available for around 20 hours or as needed next week. However, I won't be available from 17th Oct - 24th Oct as my dad is visiting me from India.
ETA: Completion of tasks depends on the feedbacks, quicker we get through it, the sooner it gets done.
Pictures (if necessary): https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=1-2&t=mF5LHlPp9eDXLafN-1

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by sonaliagle** [comment]
https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=1-2&t=QFtsO1S4xeNcyb2v-1

**Comment by sonaliagle** [comment]
Progress : As per the feedback from our last meeting, I have expored some color options to figure out if the logo is legible in every mode

**Comment by sonaliagle** [comment]
https://docs.google.com/presentation/d/17BZz8Lzn-TxHeMF85iVDVDDsTFHG-JRQZ7yK4Mm8v10/edit?usp=sharing

**Comment by sonaliagle** [comment]
[People Depot Final Branding .pdf](https://github.com/user-attachments/files/17671080/People.Depot.Final.Branding.pdf)

**Comment by sonaliagle** [comment]
[People Depot Final Branding .pdf](https://github.com/user-attachments/files/17853489/People.Depot.Final.Branding.pdf)
Final logo + illustration idea

**Comment by shmonks** [comment]
@sonaliagle Thank you! Did you add the final logo to the PeopleDepot Figma file (see action items at the top of this issue)?

**Comment by sonaliagle** [comment]
I am adding it now @shmonks

**Comment by shmonks** [comment]
Hi @sonaliagle - for some reason I can't find the asset for the final logo itself, the one used in [the last pdf you made](https://github.com/user-attachments/files/17853489/People.Depot.Final.Branding.pdf), in the Figma file. Would you mind adding it to the new page I created for the final designs, together with the favicon asset: https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=358-14&t=dXoQ2rRRQO0WYllv-0. Thanks!

**Comment by shmonks** [comment]
@sonaliagle Apologies - I just saw that you put the digital assets in the Google Drive! I'll add them to the Figma file too. Thanks again.

**Comment by shmonks** [comment]
Link to Figma file with final logo and favicon for PeopleDepot: https://www.figma.com/design/9IFhCrkG20bNQUgV6gts3O/People-Depot-Main-File?node-id=0-1&p=f&t=z8Qoj6JTo6ZmB6Lp-0
