### ISSUE TITLE
Update Table: recurring_event (rename to event)

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#173]
### Overview
We need to update the recurring_event table model (now the event table model) to utilize the practice area table instead of the outdated role table.

#### Details
The initial model issue is #14

Discussion leading to this change is here: https://github.com/hackforla/peopledepot/discussions/170

### Action Items
- [x] Update schema information
  - [x] add/remove given columns from [Entity Relationship Diagram (ERD)](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view)
  - [x] add/remove given columns from [PD: Table and Field definitions](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1572339087)
  - [x] make additional schema changes (if needed)
  - [x] remove the ERD/SS update label after these changes are made.
     - Permission is needed to edit the ERD and table spreadsheet.
- [x] Rename Django model
- [x] Update existing Django model
- [ ] Write a test for the new relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project) if any.
- [x] Update API end point
- [x] Update API unit tests
- [ ] Document the endpoint in Swagger
- [ ] Take #88 out of the ice box

#### Columns to Remove
- [x]  must_roles - int[] (role_id)
- [x]  should_roles - int[] (role_id)
- [x]  could_roles - int[] (role_id)

#### Columns to Add
- [x]  must_attend - JSON[]
- [x]  should_attend - JSON[]
- [x]  could_attend - JSON[]

#### Additional Changes
- [x]  Change name from recurring_event to event
  - [x] in schema
  - [x] in django
- [x]  Add example JSON to the ERD somehow
     - This could be handled by adding a stickynote to the ERD, or maybe a link to a new tab in the spreadsheet.
JSON Example:
```
[{practice_area: engineering, permission_level: practiceLeadProject},{practice_area: pm, permission_level: practiceLeadProject}]
```
### Resources
- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint

**Comment by fyliu** [comment]
- I forgot about this issue. Thanks @Neecolaa for pointing this out. This one should've been done before #88. I was working on #88 and it 
  - deletes the `event` and `event_history` tables and 
  - renames `recurring_event` to `event`.

- So @Neecolaa applied the schema changes from this issue to the new `event` table. I think we can close this issue and update and implement #47. That table hasn't been made into a django model yet.

Related tasks:
- [ ] update #47 with the new table structure
- [ ] create issue to remove `recurring_event` table and django model if it's not already created
- [ ] write note in #49 about it being removed

**Comment by Neecolaa** [comment]
Pull request #85 already added the `recurring_event` table. It seems more worth it to just rename that table, rather than removing it now and later replacing it with a slightly different `event` table.

Update Table issues are only for when a table is already created. If not, we just revise the existing issue and leave a comment.

**Comment by fyliu** [comment]
Okay, We'll do the rename then. I was thinking of going the other way. We'll see if django is smart enough to do a database rename or if it'll drop and create a new table.

**Comment by fyliu** [comment]
Looks like some changes in this issue wasn't implemented in code. I'm creating a new issue for them.
