### ISSUE TITLE
Evaluate django-simple-history / django-auditlog for history tables

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#181]
### Overview

We would like to know if django-simple-history can fulfill our needs of keeping history of certain tables. We can potentially save time and developer efforts.
The package automatically keeps track of change history metadata like who made the change.

### Details/Requirements

- [x] should be useful for #49 (issue closed)
  - An event record has a long life with cancellations and overrides, and metadata about who made those changes should be useful
- [ ] not useful for ~#37~ (probably need this afterall)
  - needs to hold the old permission records that are no longer in effect
  - new permission records are created for each update, so there's no updating each record to keep track of
- [ ] should be useful for #67
  - needs the history of the status field for each project

### Action Items

- [ ] install plugin into django and test the functionality
- [ ] evaluate whether it can fulfil our needs
- [ ] document usage if it's useful
- [ ] release the dependency on the following issues and if there are no other dependencies, move them from the icebox to the new issue approval column and add the `ready for dev lead` label.
   - [ ] #49
   - [ ] ~#37~ no longer applicable
   - [ ] #67

### Resources/Instructions
- This issue was a part of #49
- [django-simple-history](https://github.com/jazzband/django-simple-history)

**Comment by fyliu** [comment]
We need to come up with requirements for what we want to be able to do with a history model. Maybe document it in this issue or create a separate issue for it.

**Comment by ExperimentsInHonesty** [comment]
We will definitely create a separate issue for requirements.  That issue will be this issue's dependency

**Comment by fyliu** [comment]
I'm trying to figure out why I crossed out the `project_status_history` table from requirements. Looks like that table is still part of the schema and needs a history. It could be that I thought it's not something that `djang-simple-history` can solve. I think it's still worth keeping it in the list since this is an evaluation issue, to see if it can be satisfied as well.

I'm going to un-cross it.

**Comment by fyliu** [comment]
I updated the Details section with information on whether I think the library can help what that table needs. It turns out that information was at the bottom of the issue description.

**Comment by fyliu** [comment]
I came across other potential solutions that I need to compare with this package. Setting this for dev-lead.

**Comment by shmonks** [comment]
@fyliu I'm just looking through the Ice Box - since this issue is the sole remaining dependency on #37, I wonder whether it's time to prioritize it?

**Comment by shmonks** [comment]
@fyliu I see from changes to the top comment here that #37 no longer has a dependency on this issue, so I'm going to release #37. How about #67 - does that still need to be dependent on this issue?

**Comment by fyliu** [comment]
Adding [django-auditlog](https://django-auditlog.readthedocs.io/en/latest/usage.html) as a candidate. It doesn't have undo functionality but just provides a history of changes applied to model objects.

**Comment by fyliu** [comment]
### Requirements

3 weeks ago at the meeting, we established what's needed from the history tables such as UserPermissionHistory.

- record events that happened to the object (a permission), who updated it and when
- be able to retrieve the full history of events for display
- (new) retrieve deleted permissions as well (soft delete)

### Progress Update

I've been working on this issue for about 3 weeks but didn't update progress until now.

#### Before

I tried logging the `Faq` model and it tracked the creation and changes for the objects. But that model doesn't have the FKs that UerPermission does.

#### In progress

I needed to try the `UserPermission` model itself, so I created some users, projects, and permission objects. I'm doing it partly in Django shell and partly in Django admin. I can create users in Django shell, but it can't record which user did the actions without some hack. I'm thinking of finishing doing it the current way to see that we can retrieve a list of object changes for each object, and that'll be the end of the usefulness of this approach.

#### Next steps

The next approach will be either coding the object changes in API tests or in Django shell with user logins or some other hack to set the action user, which would replace the manual clicking in the Django admin. I'm leaning towards the API tests, since they're close to high-level descriptions of how API clients would use the system. We can do it once and then do similar things for other tests later.

Along the way, I think we'll discover things that are missing from the API that clients might need.

**Comment by fyliu** [comment]
### Progress Update

- It's still a manual process to add the users and create/update the projects, permissions, etc.
- I'm able to register models for audit logging and retrieve the logs for specific objects. So I think it would satisfy our needs.
   - There's a script that helps retrieve and format the output

#### Need

- We need a new endpoint to return the history. What should it be?
   - `/userpermission/:pk/history`?

#### Todo

- try and confirm it works when using the API
- create an API endpoint to return the log for one logged object (one permission's change history)
   - we would need to set access restrictions on the API endpoint rather than on the DB model for this
   - This is essentially the same logic in script mentioned above.
- add API test to go through the logging and check that it returns the correct actions and changes.

### How to update permissions

- Manual:
   1. Login to Django Admin site using an admin/staff user.
   2. View the permissions list and choose to view an individual permission.
   3. Make changes and save. There's Django hooks that'll create the AuditLog entry automatically.
- Via REST API:
   1. Login to API.
   2. Make changes to a permission. It'll create the AuditLog entry automatically.
      1. GET UserPermisison
      2. GET UserPermission/PK
      3. PATCH UserPermission/PK with changed fields

### How to print the histories

- There's some helper script that help with this. I think we can convert them into useful code to check in.

1. Get into Docker container shell

	```
	./scripts/shell.sh
	```

1. Get into Django shell
	```
	python manage.py shell
	```

1. Print the permission history for a `username`

	```
	from core import audit
	audit.print_user_permission_histories("fang")
	```

### Examples of log entries:

<details>
  <summary>History for a Faq object: CREATE and UPDATE entries</summary>

```
>>> audit.print_whats_git_faq_histories()                                                                                                                                                                                                      
[
    {
        'permission': "Updated What's git",
        'entries': [
            {'id': 5, 'when': '2026-04-02 22:18:09', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'tool_tip_name': {'before': '', 'after': 'whats-git'}}},
            {
                'id': 2,
                'when': '2026-03-21 04:11:29',
                'action': 'UPDATE',
                'actor': 'admin@admin.com',
                'changes': {'answer': {'before': "It's a tool that tracks changes to source code files", 'after': "It's a tool that manages source code files"}}
            },
            {
                'id': 1,
                'when': '2026-03-21 04:10:17',
                'action': 'CREATE',
                'actor': 'admin@admin.com',
                'changes': {
                    'uuid': {'before': 'None', 'after': '0d0224b9-63f9-4ff9-b35a-f3818db4e0e7'},
                    'answer': {'before': 'None', 'after': "It's a tool that tracks changes to source code files"},
                    'question': {'before': 'None', 'after': "What's git"},
                    'created_at': {'before': 'None', 'after': '2026-03-21 04:10:17.975948'},
                    'updated_at': {'before': 'None', 'after': '2026-03-21 04:10:17.975982'},
                    'tool_tip_name': {'before': 'None', 'after': ''}
                }
            }
        ]
    }
]
```
</details>

<details>
  <summary>History for Alice user: CREATE and UPDATE entries</summary>

```
>>> audit.print_alice_permission_histories()                                                                                                                                                                                                   
[                                                                                                                                                                                                                                              
    {                                                                                                                                                                                                                                          
        'permission': 'Updated User: alice / Permission Type: memberProject / Project: TDM Calculator / Practice Area: Development',                                                                                                           
        'entries': [                                                                                                                                                                                                                           
            {'id': 16, 'when': '2026-04-08 06:30:45', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'project': {'before': 'People Depot', 'after': 'TDM Calculator'}}},                                                   
            {'id': 15, 'when': '2026-04-08 06:06:28', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'permission_type': {'before': 'memberGeneral', 'after': 'memberProject'}}},                                           
            {                                                                                                                                                                                                                                  
                'id': 14,                                                                                                                                                                                                                      
                'when': '2026-04-08 06:06:20',                                                                                                                                                                                                 
                'action': 'CREATE',                                                                                                                                                                                                            
                'actor': 'fang_staff@example.com',                                                                                                                                                                                             
                'changes': {                                                                                                                                                                                                                   
                    'user': {'before': None, 'after': 'alice@example.com'},                                                                                                                                                                    
                    'uuid': {'before': 'None', 'after': '93530b41-701b-450a-9731-609e2e985613'},                                                                                                                                               
                    'project': {'before': None, 'after': 'People Depot'},                                                                                                                                                                      
                    'created_at': {'before': 'None', 'after': '2026-04-08 06:06:20.422707'},                                                                                                                                                   
                    'updated_at': {'before': 'None', 'after': '2026-04-08 06:06:20.422745'},                                                                                                                                                   
                    'practice_area': {'before': None, 'after': 'Development'},                                                                                                                                                                 
                    'permission_type': {'before': None, 'after': 'memberGeneral'}                                                                                                                                                              
                }                                                                                                                                                                                                                              
            }                                                                                                                                                                                                                                  
        ]                                                                                                                                                                                                                                      
    }                                                                                                                                                                                                                                          
]                                                                                                                                                                                                                                              
```
</details>

<details>
  <summary>History for Fang user: missing CREATE entries</summary>

```
>>> audit.print_fang_permission_histories()
[
    {
        'permission': 'Updated User: fang / Permission Type: memberGeneral/ Project: Jobs for Hope / Practice Area: Development',
        'entries': [
            {'id': 10, 'when': '2026-04-02 22:32:48', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'permission_type': {'before': 'adminProject', 'after': 'memberGeneral'}}},
            {'id': 6, 'when': '2026-04-02 22:31:30', 'action': 'UPDATE', 'actor': 'admin@admin.com', 'changes': {'permission_type': {'before': 'memberGeneral', 'after': 'adminProject'}}}
        ]
    },
    {
        'permission': 'Updated User: fang / Permission Type: memberGeneral/ Project: TDM Calculator / Practice Area: Development',
        'entries': [
            {'id': 12, 'when': '2026-04-02 22:33:13', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'permission_type': {'before': 'memberProject', 'after': 'memberGeneral'}}},
            {'id': 8, 'when': '2026-04-02 22:31:53', 'action': 'UPDATE', 'actor': 'admin@admin.com', 'changes': {'permission_type': {'before': 'memberGeneral', 'after': 'memberProject'}}}
        ]
    },
    {
        'permission': 'Updated User: fang / Permission Type: practiceLeadJrProject / Project: People Depot / Practice Area: Development',
        'entries': [
            {'id': 13, 'when': '2026-04-08 05:04:07', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'permission_type': {'before': 'practiceLeadProject', 'after': 'practiceLeadJrProject'}}},
            {'id': 11, 'when': '2026-04-02 22:33:04', 'action': 'UPDATE', 'actor': 'fang_staff@example.com', 'changes': {'permission_type': {'before': 'memberProject', 'after': 'practiceLeadProject'}}},
            {'id': 7, 'when': '2026-04-02 22:31:43', 'action': 'UPDATE', 'actor': 'admin@admin.com', 'changes': {'permission_type': {'before': 'practiceLeadProject', 'after': 'memberProject'}}}
        ]
    }
]
```
</details>

**Comment by fyliu** [comment]
### `auditlog_logentry` Table

<details>
  <summary>view table in admin site as image</summary>
<img width="1531" height="1030" alt="Image" src="https://github.com/user-attachments/assets/c43d0440-84d9-4392-a6c4-cca6a3ac4986" />
</details>

#### Table Description
```
table_name	column_name	data_type	is_nullable
auditlog_logentry	id	integer	NO
auditlog_logentry	object_pk	character varying	NO
auditlog_logentry	object_id	bigint	YES
auditlog_logentry	object_repr	text	NO
auditlog_logentry	action	smallint	NO
auditlog_logentry	changes	jsonb	YES
auditlog_logentry	timestamp	timestamp with time zone	NO
auditlog_logentry	actor_id	uuid	YES
auditlog_logentry	content_type_id	integer	NO
auditlog_logentry	remote_addr	inet	YES
auditlog_logentry	additional_data	jsonb	YES
auditlog_logentry	serialized_data	jsonb	YES
auditlog_logentry	cid	character varying	YES
auditlog_logentry	changes_text	text	NO
auditlog_logentry	remote_port	integer	YES
auditlog_logentry	actor_email	character varying	YES
```


#### Table Data
[auditlog_logentry.csv](https://github.com/user-attachments/files/26621482/auditlog_logentry.csv)


<details>
  <summary>view table here</summary>


| id | object_pk                            | object_id | object_repr                                                                                                  | action | changes                                                                                                                                                                                                                                                                                                                                                                                                                               | timestamp                     | actor_id                             | content_type_id | remote_addr | additional_data | serialized_data | cid | changes_text | remote_port | actor_email            |
| -- | ------------------------------------ | --------- | ------------------------------------------------------------------------------------------------------------ | ------ | ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ----------------------------- | ------------------------------------ | --------------- | ----------- | --------------- | --------------- | --- | ------------ | ----------- | ---------------------- |
| 1  | 0d0224b9-63f9-4ff9-b35a-f3818db4e0e7 |           | What's git                                                                                                   | 0      | {"uuid": ["None", "0d0224b9-63f9-4ff9-b35a-f3818db4e0e7"], "answer": ["None", "It's a tool that tracks changes to source code files"], "question": ["None", "What's git"], "created_at": ["None", "2026-03-21 04:10:17.975948"], "updated_at": ["None", "2026-03-21 04:10:17.975982"], "tool_tip_name": ["None", ""]}                                                                                                                 | 2026-03-21 04:10:17.977598+00 | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 9               | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 2  | 0d0224b9-63f9-4ff9-b35a-f3818db4e0e7 |           | What's git                                                                                                   | 1      | {"answer": ["It's a tool that tracks changes to source code files", "It's a tool that manages source code files"]}                                                                                                                                                                                                                                                                                                                    | 2026-03-21 04:11:29.51758+00  | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 9               | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 3  | a685e841-5b99-49b9-ab71-c731d5d492f3 |           | How to create a new model                                                                                    | 0      | {"uuid": ["None", "a685e841-5b99-49b9-ab71-c731d5d492f3"], "answer": ["None", "details"], "question": ["None", "How to create a new model"], "created_at": ["None", "2026-04-02 22:17:43.585488"], "updated_at": ["None", "2026-04-02 22:17:43.585555"], "tool_tip_name": ["None", ""]}                                                                                                                                               | 2026-04-02 22:17:43.587039+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 9               | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 4  | 2d41292f-4535-44fe-a4e4-312ea8b062bc |           | How to create a PR                                                                                           | 0      | {"uuid": ["None", "2d41292f-4535-44fe-a4e4-312ea8b062bc"], "answer": ["None", "this is how"], "question": ["None", "How to create a PR"], "created_at": ["None", "2026-04-02 22:17:57.834489"], "updated_at": ["None", "2026-04-02 22:17:57.834507"], "tool_tip_name": ["None", ""]}                                                                                                                                                  | 2026-04-02 22:17:57.836139+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 9               | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 5  | 0d0224b9-63f9-4ff9-b35a-f3818db4e0e7 |           | What's git                                                                                                   | 1      | {"tool_tip_name": ["", "whats-git"]}                                                                                                                                                                                                                                                                                                                                                                                                  | 2026-04-02 22:18:09.076062+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 9               | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 6  | d3285518-3839-4df9-b5ea-bd6b090a3383 |           | User: fang / Permission Type: adminProject/ Project: Jobs for Hope / Practice Area: Development              | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000008", "00000000-0000-0000-0000-000000000004"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:31:30.943215+00 | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 23              | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 7  | 7f3637cf-239a-4b4c-bb95-2615d718b79b |           | User: fang / Permission Type: memberProject/ Project: People Depot / Practice Area: Development              | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000005", "00000000-0000-0000-0000-000000000007"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:31:43.716013+00 | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 23              | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 8  | 4d5658da-f826-4e4b-b6b2-0df47e2f3c53 |           | User: fang / Permission Type: memberProject/ Project: TDM Calculator / Practice Area: Development            | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000008", "00000000-0000-0000-0000-000000000007"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:31:53.102798+00 | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 23              | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 9  | 717dfd6f-60ab-4b05-86b9-8b4c0cd5196e |           | User: admin1111 / Permission Type: practiceLeadJrProject/ Project: People Depot / Practice Area: Development | 2      | {"user": ["48ea902f-cb14-4a47-b86f-ca700bf63b4b", "None"], "uuid": ["717dfd6f-60ab-4b05-86b9-8b4c0cd5196e", "None"], "project": ["fa104f6d-9495-4f13-b367-616a2eec09f8", "None"], "created_at": ["2026-03-22 04:01:54.079036", "None"], "updated_at": ["2026-03-22 04:02:09.845253", "None"], "practice_area": ["00000000-0000-0000-0000-000000000001", "None"], "permission_type": ["00000000-0000-0000-0000-000000000006", "None"]} | 2026-04-02 22:32:09.112582+00 | 48ea902f-cb14-4a47-b86f-ca700bf63b4b | 23              | 172.20.0.1  |                 |                 |     |              |             | admin@admin.com        |
| 10 | d3285518-3839-4df9-b5ea-bd6b090a3383 |           | User: fang / Permission Type: memberGeneral/ Project: Jobs for Hope / Practice Area: Development             | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000004", "00000000-0000-0000-0000-000000000008"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:32:48.31811+00  | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 11 | 7f3637cf-239a-4b4c-bb95-2615d718b79b |           | User: fang / Permission Type: practiceLeadProject/ Project: People Depot / Practice Area: Development        | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000007", "00000000-0000-0000-0000-000000000005"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:33:04.356735+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 12 | 4d5658da-f826-4e4b-b6b2-0df47e2f3c53 |           | User: fang / Permission Type: memberGeneral/ Project: TDM Calculator / Practice Area: Development            | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000007", "00000000-0000-0000-0000-000000000008"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-02 22:33:13.083749+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 13 | 7f3637cf-239a-4b4c-bb95-2615d718b79b |           | User: fang / Permission Type: practiceLeadJrProject / Project: People Depot / Practice Area: Development     | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000005", "00000000-0000-0000-0000-000000000006"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-08 05:04:07.00341+00  | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 14 | 93530b41-701b-450a-9731-609e2e985613 |           | User: alice / Permission Type: memberGeneral / Project: People Depot / Practice Area: Development            | 0      | {"user": ["None", "447b44f0-84a0-44a7-a542-80f3f64edb2d"], "uuid": ["None", "93530b41-701b-450a-9731-609e2e985613"], "project": ["None", "fa104f6d-9495-4f13-b367-616a2eec09f8"], "created_at": ["None", "2026-04-08 06:06:20.422707"], "updated_at": ["None", "2026-04-08 06:06:20.422745"], "practice_area": ["None", "00000000-0000-0000-0000-000000000001"], "permission_type": ["None", "00000000-0000-0000-0000-000000000008"]} | 2026-04-08 06:06:20.42362+00  | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 15 | 93530b41-701b-450a-9731-609e2e985613 |           | User: alice / Permission Type: memberProject / Project: People Depot / Practice Area: Development            | 1      | {"permission_type": ["00000000-0000-0000-0000-000000000008", "00000000-0000-0000-0000-000000000007"]}                                                                                                                                                                                                                                                                                                                                 | 2026-04-08 06:06:28.464738+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
| 16 | 93530b41-701b-450a-9731-609e2e985613 |           | User: alice / Permission Type: memberProject / Project: TDM Calculator / Practice Area: Development          | 1      | {"project": ["fa104f6d-9495-4f13-b367-616a2eec09f8", "604550e1-b991-45e4-bd17-ee05f8b2c489"]}                                                                                                                                                                                                                                                                                                                                         | 2026-04-08 06:30:45.332801+00 | 0a343487-ecc5-4757-a385-b19906b3f505 | 23              | 172.20.0.1  |                 |                 |     |              |             | fang_staff@example.com |
</details>

**Comment by fyliu** [comment]
From the meeting:
- A project permission's permission_type can't be memberGeneral. It must be one of the project types, or "noPermission" if the user is off-boarded from the project.
- We need a "noPermission" permission_type for this
- A user starts at "noPermission" and then becomes memberGeneral after onboarding?
- A user can have a global permission, which can be memberGeneral, without an associated project, and also have a project permission, like memberProject of People Depot.
- A user's project permissions won't be deleted, but will be kept so its history can be retrieved.
- A project permission's delete time is the timestamp when its permission_type is set to "noPermission"

Endpoints that could be helpful:
/userpermission/:pk/history
/user/:pk/project/:pk/permission/history
/project/:pk/user/:pk/permission/history

Workflow of project admin
1. Get self user
2. Get user's projects list to display on UI, where user chooses one to manage.
3. Get project's users list to display on UI, where user chooses one to manage its permission
GET /project
GET /project/:pk/users
GET /user/:pk/project/:pk/permission/history

**Comment by fyliu** [comment]
WIP permissions state diagrams
<details>
  <summary>Organization</summary>

```mermaid
---
title: Organization Permission
config:
  layout: dagre
---

stateDiagram-v2
    [*] --> noPermission: user self-registers OR adminBrigade adds user's email
    noPermission --> memberGeneral: accepted user checks
    memberGeneral --> noPermission: offboarded
```
</details>

<details>
  <summary>Project</summary>

```mermaid
---
title: Project Permission
---

stateDiagram-v2
    memberGeneral --> memberProject : projectAdmin or high can create this new permission object
    memberProject --> practiceLeadProject : adminProject or higher can make this change
    memberProject --> adminProject: adminBrigade or higher can make this change
    memberProject --> noPermission: offboarded
    practiceLeadProject --> noPermission: offboarded
    adminProject --> noPermission: offboarded
```
</details>

**Comment by fyliu** [comment]
This is put on hold for 2 weeks waiting for the work being done on seed data.

Once the data types are reviewed and settled, we can then create meaningful sample data according to those.
