### ISSUE TITLE
Epic: Initial Deployment

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#218]
### Overview
These are the tasks that need to be done for deploying people depot

### Action Items

- [ ] Create a deployment docker setup
- [ ] converting Dockerfile to an alpine base image
- [ ] set up pyup for security updates
- [ ] 

### Resources/Instructions
- [production dockerfile](https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/#production-dockerfile)

**Comment by fyliu** [comment]
I think we should have the AWS deployment discussion here since this is the epic that includes all the others. See the screenshot of the issues hierarchy from above:

![Image](https://github.com/user-attachments/assets/1605892c-6215-41b8-b002-41b53f7b6263)

- #219 was skipped and that's okay. We can work on it out of order.
- #297 is to deploy peopledepot to a dev instance in incubator. I don't think we want to deploy a production instance yet until we have a chance to work out some issues with just the dev instance. We should encounter issues when clients start integrating with the backend that could require us to adjust some configurations.
- 325-330 were meant for a non-ops person in the peopledepot team to work with ops in small steps to build up to the deployment. Someone from ops would be able to do everything in one step as Alex has done. So he just did the last step #330.
- But to review if we still want to do 325-329
   - #325 depends on if ops has a checklist (they don't). So we would help them create one as the person from our team goes through the other steps. That didn't happen, so we don't have the knowledge to help with that. This means ops will have to work on it themselves. But we're done with that one.
   - #326 for the dev instance deployment, the existing VRMS user pool is sufficient. We might discover new requirements when VRMS or KB integrates with our backend. Those requirements will be useful for the production deployment, but we don't have anything to do there for that issue.
   - #328 the API clients are attached to the user pool and we will discover what we need when various clients integrate with the dev backend and we'll use that for production. But we don't need to do anything there either.
   - #329 this is provisioned automatically by the terraform config that Alex created. So this is done.
   - #327 is just an epic that contains 326, 328, 329

**Comment by fyliu** [comment]
See also comments in #325
Max's update with information from Ops: https://github.com/hackforla/peopledepot/issues/325#issuecomment-2741671225
My response: https://github.com/hackforla/peopledepot/issues/325#issuecomment-2741757113

**Comment by gmgonzal** [comment]
Sounds good @fyliu, thank you for the background info! One thing I can do here is work with devops team to get a deployment checklist finalized (will post updates to #325).
