### ISSUE TITLE
PeopleDepot: PM Agenda

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#28]
### Overview

We mainly need to onboard Eric Vennemeyer to PeopleDepot

### Action Items

- [ ] Onboard Eric Vennemeyer #27
- [ ] Discuss using the next month's time to make PeopleDepot locally usable for VRMS development
- [ ] Make milestones for PeopleDepot

### Resources
[Roadmap for the near future](https://github.com/hackforla/peopledepot/wiki/Quick-roadmap)

**Comment by fyliu** [comment]
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #

### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] Bonnie
       - [ ] Fang
       - [ ] Nicole
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
    - [ ] #33

### New Items
- [ ] Discuss the feasibility of using the next month's time to #29
- [ ] #34
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
- Fang will be away/mostly unavailable for a month's time in less than 2 months
- [Roadmap for the near future](https://github.com/hackforla/peopledepot/wiki/Quick-roadmap)

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
- The template for the team meeting agenda needs an update https://github.com/hackforla/peopledepot/issues/103

**Comment by luca-navarrete** [comment]
Add to the next agenda: 
```
- [ ] Review with Bonnie 
  - [ ] Slack channels (active/dormant/archived)
  - [ ] Slack channel pins and bookmarks
```

**Comment by shmonks** [comment]
### 2024-09-10 PM Buffer meeting notes - @fyliu, @vanessaavviles, @shmonks 
- Discussed progress on revising both the PD wiki and mkdocs site
- Re: mkdocs: the [Contributing section](https://hackforla.github.io/peopledepot/CONTRIBUTING/) is too long, and needs splitting up into separate pages
    - Perhaps we should have a Contributing **folder** instead, with general info for all-comers, and then separate pages/subfolders for developers, so it's not too much information for those who don't need it?
    - Perhaps we should have separate pages/folders with info for users and possibly PMs too (though perhaps better to keep all PM info on the wiki where it can be more easily edited)?
    - Perhaps the Tools and Developer Guides sections should be moved to the top level of the structure?
    - Perhaps all the coding-related info should be moved into a folder of its own?
    - Perhaps we should use a top-level main menu bar like [this example](https://jimporter.github.io/bfg9000/latest/) (to keep left-hand menu clean and relevant), and include a Contents section/page on the PD mkdocs hompage?
- [ ] Re: wiki, I will do pre-issue work to gauge best scope and action steps then write an issue for thorough revision
- [ ] Once @fyliu has got to a point where he feels OK with the mkdocs site, we'll think again about the best way to structure it
- [ ] Once we've got both mkdocs and wiki closer to complete, we'll coordinate to get them properly linked to each other (ideally, with links from wiki developer-related pages to mkdocs pages, so we keep the wiki clean)

**Comment by fyliu** [comment]
### Next PM Buffer meeting Agenda

- [ ] Fang: we should have an ADR (Architectural/All Decision Records) area in mkdocs to hold decisions that are applicable to the software project
   - we already have some DRs (Decision Records) in the wiki. Maybe that one decision should be moved to mkdocs
   - I feel we need to capture a little more context in the ADRs (there's templates out there we can customize and adopt)
      - number (just sequential numbers. doesn't even have to be earliest date first. Sometimes there are prior decision written down after the fact)
      - status (accepted, adopted, rejected, superceded by ADR #<number>)
      - date (I made some prior ones that can be current date maybe with a note)
      - people involved (sometimes people forget what they agreed to, but mainly to show it's a consensus of these people)
      - problem context (GH issue #, what's the problem)
      - decision drivers (what we consider to be important at this time. These should probably be tied to organization or team goals)
      - alternatives considered (list pros and cons)
      - impact (to current way of doing things, to future work)
      - decision summary (what's the decision, why, acceptable tradeoff)
