### ISSUE TITLE
Add name and external_id fields to project_url table

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#289]
### Overview

We need to add `name` and `external_id` fields to the `project_url` table, which was decided [here](https://github.com/hackforla/peopledepot/issues/78#issuecomment-1809287295).

### Action Items

- [x] Add `name` and `external_id` field to `project_url`
  - [x] [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/edit?page=0_0#)
  - [x] [Spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?pli=1#gid=1228509670)
  - [x] Update #41 issue description since it's not yet implemented
- [ ] ~check and release #78 from ice box~ (has a remaining dependency on #290) 
- [x] check and relase #41 from ice box

### Resources/Instructions

- add `name` field: What the link is called Ex: Primary Repo, Secondary Repo, Description of "other" type urls
- add `external_id` field: resource id provided by github or google
- both fields should be varchar(255) or CharField(max_length=255)
- `external_id` can be blank

**Comment by shmonks** [comment]
When submitting the PR for this issue, change the word 'fixes' to 'partially addresses'.

**Comment by shmonks** [comment]
Once assignee has completed the code portion, remove 'backend' label and put back in the Prioritized Backlog for db architect.

**Comment by dmartin4820** [comment]
It looks like the project_url table has not been created yet as shown in #41.

**Comment by fyliu** [comment]
@dmartin4820 I guess this is more of a db design change issue than a coding issue.

Would you want to check that all the items are done and close it? The work would be working with issues and documents rather than coding.

Edit the issue description and replace the "code" step with "update #41 description". Then check that the 3 steps are done and fix or comment about them if they're not editable.

Looks like @Neecolaa already made the ERD changes. Please check that it looks correct and comment here if there's a problem.

The spreadsheet has a "fields" sheet with the table names and fields, and there's an initial data sheet called something like "projectUrls" that you should check. I started updating it before I realized it's something you could do to familiarize yourself with the document. But I'm not going to bother undoing them. Please just check to make sure it's correct.

The issue #41 description also looks updated. But I see a problem with one of the new fields that you can fix. The requirements are in this issue's description so you can check them one by one.

Lastly, check if #78 dependencies are satisfied and, if so, move its status from ice box to new issue approval.

**Comment by dmartin4820** [comment]
@fyliu Under the action items of this issue, I went and checked according to your directions. My comments/questions are spread as bullet points under each checkbox.

- [ ] Add `name` and `external_id` field to `project_url`
  - [x] [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/edit?page=0_0#)
    - Name and external_id fields exist in the project_url table at the link above.
  - [x] [Spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?pli=1#gid=1228509670)
    - I found a sheet called "ProjectUrl - Empty", but not "projectUrls". Is the sheet you were referring to? The sheet includes "name" and "external_id" fields, but doesn't contain data.
    - I also found the "Fields" sheet you mentioned. It contains both "name" and "external_id" with varchar as the type.
  - [ ] Update #41 issue description
    - It looks like the url field should be specified as a URLField Django-specific data type as opposed to url varchar. The other fields look consistent with the [ERD](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/edit?page=0_0#). I can update this and check this item if we agree.
    
- [ ] check and release #78 from ice box
  - There are two dependencies:
    - #289
      - This will be completed once we resolve the steps above.
    - #290
      - It looks like I would have to take on this issue and complete the action items (which I can do with time to learn how to do this in Django):
        - [ ] create a single model in Django (defining schema)
        - [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
        - [ ] write an API end point
        - [ ] write API unit tests
        - [ ] document the endpoint

**Comment by dmartin4820** [comment]
Made some edits to my last comment to clarify the work needed to be done.

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by dmartin4820** [comment]
1. Progress: N/A. Just opened back up.
1. Blockers: N/A
1. Availability: This weekend and weekdays nights. 
1. ETA: Between tonight and next Thursday

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by Neecolaa** [comment]
- The ERD, Spreadsheet, and Issue all have the additional fields.
- #41 has been released from the ice box since this was the only dependency
- #78 has not been released from the ice box since it also has #290 as a dependency
