### ISSUE TITLE
get deployment checklist from #ops

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#325]
### Overview

As the starting point of deploying this project to AWS, we need to get the project deployment checklist from #ops (introduce yourself to the #ops channel)

### Action Items

- [x] get deployment checklist from #ops (introduce yourself to the #ops channel) and link to it from here and from #297's Resources section

  Note:
  - If the deployment checklist they have (if they have one at all) is not complete or inaccurate, we need to help them make a comprehensive one and update it in their wiki, so that it gets sign-off by them and we can use it.

- [x] if #ops creates an issue, link to it here and from #297's Resources section
- [ ] create our own issues according to what we're missing in the deployment steps and link them from here and from #297
  - [ ] at least adapt docker configs to integrate AWS resources

### After Done

- [ ] check off this issue in #297 and close if done
- [ ] move #327 from the Ice Box to New Issues Review with label ready for dev lead

### Resources/Instructions

- the checklist will likely link to instructions on how to create a terraform config which is instructions on how to provision resources such as database, cognito, etc.. We'll need that for the next issue.

**Comment by gmgonzal** [comment]
Hi Folks,

I met up with the ops team yesterday, here are some notes:

- there is no deployment checklist. I can work with the ops team to get one created.
- there is a PeopleDepot project already defined in Incubator (Incubator is the devops deoployment container) with terraform config files.
  - repo: https://github.com/hackforla/incubator
  - path: /incubator/terraform/projects/people-depot/
- no issue created by ops

Questions/TODO:
- [ ] What items should be included in the deployment list?
  - So far, we have:
    - How to create a terraform config file to configure AWS resources.
- [ ] Who is the POC that worked to get PeopleDepot setup in Incubator?

**Comment by gmgonzal** [comment]
sounds good @fyliu. I can help recheck the issues with Alex to see where we stand and if there is anything else needed.

**Comment by gmgonzal** [comment]
I synced with Alex from devops, the following resources have been configured for the PeopleDepot development environment:

- DNS Entry
- Database
- Random Password
- API Secrets
- Backend App Container

Question:

Devops is under the impression that PeopleDepot is currently using the VRMS User pool. If so, would we like to continue using the VRMS user pool or create a new one?

TODO:

- [ ] discuss setting up a deployment checklist with devops. ETA: 3/27

**Comment by fyliu** [comment]
This deployment checklist is supposed to be for the benefit of #ops in the case that they don't have one. They can learn from our deployment and create a checklist to guide the deployment of other projects.

> Now we have to decide what we want to carry over or add/remove for the production deployment.

The resources look good, but we're not ready for a production deployment yet. We need to create a production dockerfile within peopledepot first. Actually, we should use create the production Dockerfile to use in the dev deployment.

I think the next step is to tell VRMS about the dev deployment when we're ready so they can start using it for their dev deployment. We're still missing critical functionality in the peopledepot backend before it's usable by VRMS.

Then we create a production deployment with a new user pool for real data.

> Devops is under the impression that PeopleDepot is currently using the VRMS User pool. If so, would we like to continue using the VRMS user pool or create a new one?

The VRMS user pool is fine for the dev deployment. We would want to have a separate pool for real data for production deployment.

**Comment by fyliu** [comment]
We should continue in #218 just to keep things in one place. I pasted the last comments there.

**Comment by fyliu** [comment]
@gmgonzal are you still working on this? Your last comment was [this](https://github.com/hackforla/peopledepot/issues/218#issuecomment-2744267488) in the other issue.

I want to close this issue or move it to Ops since we have our dev deployment on the PeopleDepot side.
