### ISSUE TITLE
Epic: API issues and security

### ISSUE THREAD

**Issue by ethanstrominger** [hackforla/peopledepot#337]
### Dependencies / Action Items
- [ ] Implement user create 
- [ ] Implement user permissions security
- [ ] API to get token
- [ ] create shell scripts for doing get, update, and create
- [ ] create Wiki for explaining security
- [x] configurable security for user
- [ ] create correct configuration for user
- [ ] document field security for all tables with field level security
- [ ] document row level security for all tables with row level security
- [x] user permission table
- [ ] change IsAuthenticated to isAuthenticatedOrReadOnly - one for each table
- [ ] change documention to say isAuthenticatedOrReadOnly
- [ ] disable puts for all APIs

### Overview

Catch all for API and security issues

### Action Items
See dependencies
