### ISSUE TITLE
Epic: collect needed documentation

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#378]
### Overview

This issue tracks the documentation that needs to be added and the issue/pr where they would've been helpful in. The intention is to make it easy to note any missing documentation without having to create the issue at the same time.

### Action Items

- [x] [PR review guide](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2335177512): #419 
- [x] Django: [How to combine migrations](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2339280759) #421 
- [x] Git: [How to quickly checkout a PR](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2369108593) #422 
- [x] Git: [How to add a git alias](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2369118008) #423 
- [x] Django, Git: [How to resolve migration conflict](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2378028404) #424 
- [x] Git: [How to apply changes from one file to a different file](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2380299270) #425
- [x] Git: [How to combine the last several commits into one](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2461030505) #450
- [ ] Git: [How to update the docker compose command](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2628262106) 
- [x] Docker: [How to use new syntax replacing `docker-compose`](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2628262106)
- [ ] Git: [Add troubleshooting section for GitHub SSH keys (for first time users or new machine)](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2568603531)

#### How to use

1. Add a new comment for each documentation item needed using a copy of this template

   ```
   ### What's needed

   - Description of what the missing documentation is about

   ### Draft (if written)

   - Link to external docs with instructions (if applicable)

   ### Where it's useful

   - Link to what prompted the need for this change/addition (if applicable)
   - Situation where this could be used
   
   ### Where to put this
   
   **contributing docs** should go in the `/docs/contributing/` folder or sub-folders:
   - **how to guides** --> `/docs/contributing/howto/`
   - **tutorials** --> `/docs/contributing/tutorial/`

   ### Audience

   - Who or what role needs to perform this action

   ### Tags

   - git, django, etc.
   ```

1. Add an action item here, linking to the comment below

1. Create an issue to add the documentation (can be done later by another person)
  
   - Then, hide the original comment and add the new issue # to the action item

1. Work on the documentation issue and check off the action item (can be done later by yet another person)

**Comment by fyliu** [comment]
### What's needed

Common things to look for in a PR review
- make sure the PR destination is `peopledepot/main`

### Where it's useful

- https://github.com/hackforla/peopledepot/pull/376#pullrequestreview-2287426896

**Comment by fyliu** [comment]
### What's needed

Django: How to combine migrations

Say `max_migration.txt` is at `0027_...` and you want to combine 0025-0027 into one.

1. Roll back `core` app migrations to `0024`

    ```bash
    ./script/migrate.sh core 0024
    ```

1. Delete unwanted migration files

    ```bash
    rm app/core/migrations/00{25,26,27}_*
    ```

1. Recreate `max_migration.txt` for `core` app

    ```bash
    docker-compose exec web python manage.py create_max_migration_files --recreate core
    # the file core/max_migration.txt should contain "0024_..."
    ```

1. Create combined migration file for `core` app

    ```bash
    ./script/migrate.sh core
    ```

### Where it's useful

- Many initial passes for PRs have multiple migration files that should really be a single create table migration.

**Comment by fyliu** [comment]
### What's needed

How to quickly checkout a PR

Setup: add this git alias to your global git config

```bash
[alias]
    pr = !sh -c \"git fetch upstream pull/${1}/head:pr/${1} && git switch pr/${1}\"
```

Usage:

To check out PR #383 to a local branch called `pr/383`, run this.
```bash
git pr 383
```

Notes:

- This works only with github, I believe.
- The alias assumes the PRs come from a remote called `upstream`.

### Where it's useful

- This can be useful for all PR reviews
- I've been using it for a while, but I thought about adding it to the docs while reviewing #383. No special reason it's that PR.

**Comment by fyliu** [comment]
### What's needed

How to add git alias to the global git config

1. Run this in the terminal to open an editor to to edit the global git config file.

    ```bash
    git config --global -e
    ```

1. Add the git alias under the `[alias]` section and save the file.
1. The alias is now available for use.

### Where it's useful

- When another part of the doumentation says to add a git alias, this is how.

**Comment by fyliu** [comment]
### What's needed

How to resolve migration conflicts

Let's say you're rebasing and the `max_migration.txt` file shows a conflict. That's a sign that the numbered migration files are conflicting as well. They're named differently so their conflicts don't show up in git.

In many cases, you can resolve it using the `rebase_migration` command.

In this example, let's say the conflict shows that `core/0025` and `core/0027` are in conflict.

1. Undo the rebase

    ```bash
    git rebase --abort
    ```

1. Roll back the datbase to a previous migration (any number before the ones in conflict)

    ```bash
    ./scripts/migrate.sh core 0024
    ```

1. Redo the rebase

    ```bash
    git rebase <rest of command>
    # see conflicts returned
    ```

1. Resolve the migration conflict

    ```bash
    docker-compose exec web python manage.py rebase_migration core
    ```


1. Resolve any code conflicts
1. Run all the migrations

    ```bash
    ./scripts/migrate.sh core
    ```

1. Stage all the fixes

    ```bash
    git add <max_migration.txt> <changed migration files> <fixed code files>
    ```

1. Continue rebase
    ```bash
    git rebase --continue
    ```

### Where it's useful

- PR #385 is one example
- This is helpful for PR creators when they update their PR with the latest changes from `upstream/main`

**Comment by fyliu** [comment]
### What's needed

How to apply a change from to a different file

### Draft (unfinished)

Say we have a branch that contains changes to `CONTRIBUTING.md` and that the content being changed was moved to another file: `docs/contributing/dev_environment.md`. We want to manually apply our change to the file ourselves.

1. Rebase/Merge your feature branch to `main`

1. Undo changes to `CONTRIBUTING.md`

```bash
git reset upstream/main -- CONTRIBUTING.md
```

1. Switch to our unmerged branch with the changes

```bash
git switch our-branch-original
```

1. Create a patch of the changes

```bash
git format-patch hackforla/main CONTRIBUTING.md
# only changes to CONTRIBUTING.md
# include changes since we branched off from hackforla/main
# may need to create a temporary branch where hackforla/main used to be for this command

# output:
# 0001-add-to-dev-environment.patch
```

1. Switch to rebased branch without the `CONTRIBUTING.md` changes

```bash
git switch our-branch-rebased
```

1. Apply the patch to the new file

```bash
patch -p1 docs/contributing/dev_environment.md 0001-add-to-dev-environment.patch
```

### Where it's useful

- When a hunk of text is moved between files, we can apply it cleanly manually, since `git` cannot do it automatically unless the entire file was renamed.
- Link to PR or commit where CONTRIBUTING.md is split into several files

### Audience

- Developer who made changes to a file where the place of change is moved to a different file in `main`

### Tags
-

**Comment by shmonks** [comment]
I will create issues for each of the action items [above](https://github.com/hackforla/peopledepot/issues/378#issue-2511630937), integrating Fang's updates, and labelling all but the last of them as 'good first issues'

I will also create a new issue template for documentation: see https://github.com/hackforla/website/wiki/How-to-review-pull-requests

**Comment by shmonks** [comment]
- See #419 for information missing from PR review guide

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?" **First issue created (for PR review guide) - will now adapt for the rest**
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?" **Weekend**
4. ETA: "When do you expect this issue to be completed?" **Next week**
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
@shmonks If you create a template with placeholders`[REPLACE WITH...]` then you can get together with Vanessa, and show her how to create the issues using the template.  Then she can write instructions for future documentation needs that come up.

**Comment by shmonks** [comment]
This epic now replaced by the following issues, though I still need to copy over the substance of Fang's comments above into each of them (except the first):
- #419 
- #421 
- #422 
- #423 
- #424 
- #425

**Comment by shmonks** [comment]
Please provide update
1. Progress: Done - except that I'm now thinking about creating a new issue template specifically for missing documentation issues
2. Blockers: Is that wise?
3. Availability: Friday pm, Tuesday
4. ETA: Next week
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by shmonks** [comment]
Fang agreed that a new issue template for missing documentation would be good - so I'll proceed...

**Comment by fyliu** [comment]
### What's needed

How to combine the last several commits into one.

This is not the only way but it's a fast way to achieve the goal.

1. Assume we're at the head of the PR branch with 4 commits and want to combine the 4 commits into one.
1. Soft reset to the earliest commit, with all the changes of the later commits staged.
    ```bash
    git reset --soft Head~3
    ```
1. Amend the staged changed into the earliest commit.
    ```bash
    git commit --amend --no-edit
    ```
    **note**: omit the `--no-edit` flag if you want to edit the commit message. 

### Where it's useful

- [This PR](https://github.com/hackforla/peopledepot/pull/398/commits) contained 4 commits where it helped to merge them into one before rebase it to `main`.
- this could be useful for PRs that need to be rebased to `upstream/main`, especially when there's also migration conflicts where more than one commit in the PR contain migration files. The repetitive resolving merge and migration conflicts can be simplified if the PR commits are all merged into one.

### Audience

- developers, maintainers

### Tags
- git

**Comment by shmonks** [comment]
Please provide update
1. Progress: Fang's latest comment still needs to be made into an issue of its own. 
2. Blockers: I'm wondering about the status of this epic, which might be better converted into a conversation? Or an ER? I'm guessing Fang would like to use it as a notepad for recording missing documentation issues?
3. Availability: 
4. ETA: 
5. Pictures or links* (if necessary): 

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
-

**Comment by shmonks** [comment]
### What's needed





### Where it's useful

- 
- 
- 

### Audience

- 

### Tags
-

**Comment by fyliu** [comment]
The **contributing docs** should go inside the `/docs/contributing/` folder or sub-folders

- **howto guides** --> `/docs/contributing/howto/`
- **tutorials** --> `/docs/contributing/tutorial/`


### maybe temporary locations

- **style guides** --> `/docs/contributing/style/'
  - bash **scripting** guide (example contents below)
    - set **env options** for each script (what's most common, what they mean, how to use them)
    - don't leave debug output
  - **new documentation page** guide (example contents below)
    - add **tags** to each page (example tags, how it works, which ones are strongly recommended like **reader**: "contributing"/"client", **type**: "howto"/"tutorial"/"style", **topic**, etc.)
    - **where to put** the page (what this comment is about)
    - voice style (somewhat unsure about this since I'm not a documentarian)
      - conversational for howto: "you do this", "you'll see this"
      - maybe "we" for tutorial: think of it as a longer journey - "we need to set this up", "now we're finally done"
      - etc.
    - etc.

**Comment by fyliu** [comment]
### What's needed

A guide for creating a new documentation page

I'm not sure if this falls under "style guides" or "howto"

### Draft

#### Tags

- add **tags** to each page (example tags, how it works, which ones are strongly recommended like **reader**: "contributing"/"client", **type**: "howto"/"tutorial"/"style", **topic**, etc.)

#### File location

- **where to put** the page

``` mermaid
graph TD
  A[Start] --> B{contributing/client?};
  B -->|contributing| C{content type};
  subgraph contributing [contributing docs]
  C -->|tutorial| D[/docs/tutorial/];
  C -->|how to| E[/docs/howto/];
  C -->|introductory| F[/docs/intro/];
  C -->|style guide| G[/docs/style/];
  end
  B ---->|client| H{content type};
  subgraph client [client docs]
  H -->|introductory| I[/docs/client/intro/];
  H -->|tutorial| J[/docs/client/tutorial/];
  H -->|howto| K[/docs/client/howto/];
  H -->|API| L[/docs/client/api/];
  end

```

#### Voice

- voice style (suggestion until we have a technical writer to figure this out)
    - howto guide: conversational tone - "you do this", "you'll see this"
    - tutorial: "we" tone. Think of it as a longer journey - "we need to set this up", "now we're finally done"
    - TBD

#### TBD

### Where it's useful

Someone adding a new documentation page can reference this to make sure they're making use of all the available functionalities of the docs site and the documentation is like the rest of the documentation.

There's a [comment asking where new docs pages should go](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2463614225). That's also included in this guide.

### Audience

contributors, technical writers

### Tags

howto, style guide, documentation

**Comment by shmonks** [comment]
@fyliu Do you think the guide for creating a new documentation page be best in Wiki or Mkdocs?

**Comment by fyliu** [comment]
@shmonks I was thinkin Mkdocs. Maybe it's helpful to keep it in the wiki until it's more stabilized?

Oh I see what you mean. This might be for non-developers as well. But this guide is for adding documentation to the Mkdocs site. So I'm thinking the writer will have Mkdocs running locally on their computer. But I guess the writer can also modify the text in GitHub's website and create the PR, which would automatically fix any syntax problems in the markdown, and then another writer can review and approve.

I think most of the howto guides actually needs someone with a developer background to go through them to make sure they produce the expected outcome.

What should be the process of working on an approving this type of work? Developer create the first draft and writer review and produce a final one?

**Comment by shmonks** [comment]
Yes, I imagine we'd want a review - via PR probably best, then we could assign it to whoever. It sounds like Mkdocs would be the best place to have this new guide, with a link to it from the wiki.

**Comment by fyliu** [comment]
### What's needed

- How to generate a database table definition

### Draft

- adapted from a [previous comment](https://github.com/hackforla/peopledepot/issues/429#issuecomment-2484469405) in #429

Note: These steps work only for this project's database running locally in Docker container.

#### Shorter way

1. Get table definition

    ```
    ./scripts/db.sh -c "\d core_user"
    ```

- (Optional) Get all table names

    ```
    ./scripts/db.sh -c "\dt"
    ```

#### Long way

1. Enter the database shell in the docker container

    ```
    ./scripts/db.sh
    ```

1. Get list of tables

    ```
    \dt
    ```

1. Get table definition

    ```
    \d core_user
    ```

### Where the documentation needs to go

- `/docs/contributing/howto/generate-db-definition.md`

### Where it's useful

- #429 needed a way to generate a schema table in text format.
- Other similar issues can also use this guide.
- Link to what prompted the need for this change/addition
- Situation where this could be used

### Audience

- contributor, developer

### Tags

- postgres, schema, database

**Comment by fyliu** [comment]
### What's needed

- MD file syntax

### Draft (very incomplete at the moment)

#### code block indentation

- if under a header, no indent
- if under a bullet line, indent entire block 3 or 4 spaces in GitHub, or 4 spaces in MkDocs markdown

#### lists

- bullet lists start with `-`. Standardizing so we don't have a mix of `-` and `*` bullets.
- numbered lists start with `1.`. The numbers will be autogenerated by the markdown renderer.

### Where it's useful

- a [comment ](https://github.com/hackforla/peopledepot/issues/422#issuecomment-2450843080)in #422 contains code blocks not indented enough.
- This is useful for formatting markdown files in the GitHub and MkDocs site.

### Where to put this

Most of the contents are for the MkDocs site, so `/docs/contributing/howto/format-markdown.md`
But some contents are useful for GitHub as well, so also should add a link from the Wiki.

### Audience

- contributors

### Tags

- markdown

**Comment by shmonks** [comment]
### What's needed

- Add troubleshooting section for GitHub SSH keys (for first time users or new machine).

### Draft (if written)

- Link to external docs with instructions (if applicable)

### Where it's useful

- Link to what prompted the need for this change/addition (if applicable)
- Situation where this could be used

### Where to put this

**contributing docs** should go in the `/docs/contributing/` folder or sub-folders:
- **how to guides** --> `/docs/contributing/howto/`
- **tutorials** --> `/docs/contributing/tutorial/`

### Audience

- Who or what role needs to perform this action

### Tags

- git, django, etc.

**Comment by fyliu** [comment]
@shmonks 
commenting on the SSH comment https://github.com/hackforla/peopledepot/issues/378#issuecomment-2568603531 above:
The website guide looks useful and has instructions for mac and windows.

There's benefits both for putting it in our own mkdocs vs. Engineering Cop. With the tabs widget in mkdocs, it would make the instructions look shorter (hiding the instructions for the other OS). But putting it in Engineering CoP wiki would centralize it for other teams to reference, which is also a plus.

I think the best scenario would be to put it in Engineering CoP in mkdocs. We'd need to set it up for them (which is quick, and a one time thing) and consider what, if any, maintenance they'll have to do to mkdocs other than just writing the documentation in markdown.

**Comment by del9ra** [comment]
### What's needed

- After the recent Docker updates, we need to replace the hyphen with a space in commands starting with docker-compose in script files like run.sh and migrate.sh. The hyphen is no longer needed. I encountered an issue where the docker-compose command didn’t work when I ran ./scripts/buildrun.sh

### Draft (if written)

https://docs.docker.com/compose/releases/migrate/


### Where it's useful

- Situation where this could be used
- https://github.com/hackforla/peopledepot/pull/437
- If someone tries to start Docker using the ./scripts/buildrun.sh command

### Where to put this

https://hackforla.github.io/peopledepot/contributing/dev_environment/#install-docker
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#16-dev-setup-6-build-and-serve-the-website-locally
https://github.com/hackforla/website/blob/gh-pages/CONTRIBUTING.md#i-a-few-notes-regarding-docker

### Audience

- Who or what role needs to perform this action
Backend developer

### Tags

- git, django, etc.

**Comment by fyliu** [comment]
> - After the recent Docker updates, we need to replace the hyphen with a space in commands starting with `docker-compose `in script files like run.sh and migrate.sh. The hyphen is no longer needed.

@del9ra What do you think about updating all the calls to use the new syntax in the scripts?

They made the change maybe 2+ years ago. But some recent updates starting maybe a year ago started breaking the docker-compose command.

**Comment by del9ra** [comment]
> > * After the recent Docker updates, we need to replace the hyphen with a space in commands starting with `docker-compose `in script files like run.sh and migrate.sh. The hyphen is no longer needed.
> 
> [@del9ra](https://github.com/del9ra) What do you think about updating all the calls to use the new syntax in the scripts?
> 
> They made the change maybe 2+ years ago. But some recent updates starting maybe a year ago started breaking the docker-compose command.

@fyliu Up until now, when running `./scripts/buildrun.sh`, I only had issues with `run.sh` and `migrate.sh.` But if you've run into the same problem with other scripts, then yes, it makes sense to update all the calls. By the way, I didn’t have any issues with `docker-compose` command last year. The problems only started this January.

**Comment by fyliu** [comment]
> [@fyliu](https://github.com/fyliu) Up until now, when running `./scripts/buildrun.sh`, I only had issues with `run.sh` and `migrate.sh.` But if you've run into the same problem with other scripts, then yes, it makes sense to update all the calls. By the way, I didn’t have any issues with `docker-compose` command last year. The problems only started this January.

@del9ra not all newer versions will break it. Only some updated do. I've experience it twice before, starting maybe a year ago, but not currently.

**Comment by fyliu** [comment]
In response to [my comment above](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2611274407) about moving common documentation to Engineering CoP, since they're not working on adding engineering documentation to even their wiki, I guess we'll just have to add what our team needs in our own docs for now. We can reference the website wiki where it's helpful. Maybe we should also make a local copy of the original text just in case something happens to the source page.

**Comment by fyliu** [comment]
### What's needed

- How to move a git branch from `upstream` to a forked `origin` repository

### Draft

**Note**: `upstream` and `origin` are the common naming convention for a project's primary git repository and an individual contributor's git repository. You may use other names such as `hackforla` and `mine` and substitute them in the sample commands.

1. Make sure you have an `origin` and an `upstream` remote [link to guide for creating fork and remotes for upstream and origin]
    ```bash
    git remote -v
    # The output should show 2 remote names on the left: origin and upstream
    # upstream should point to hackforla/peopledepot
    # origin should point to your fork's url
    ```

1. Checkout the feature branch
    ```bash
    git switch <branch-name>
    ```
1. Push to your fork and set the upstream branch

    ```bash
    git push -u origin <branch-name>
    ```

1. Remove the `upstream` branch
    ```bash
    git push upstream -d <branch-name>
    ```

1. [optional] Check that the upstream branch is set
    ```bash
    git branch -sb
    # the first output line should show the current branch name and then the remote branch name
   ```

### Where it's useful
- Members may not be familiar with the fork model of open source contribution. This is a guide for transitioning to the model we use at peopledepot and Hackforla.
- During a cleanup of hackforla/peopledepot repo, there were many feature branches that should really belong to the individual contributors' forks. This can be a guide for those contributors.

### Where to put this

`/docs/contributing/howto/`

### Audience

- code contributors

### Tags

- git, github
