### ISSUE TITLE
Roadmap work to be done before a feature is released

### ISSUE THREAD

**Issue by shmonks** [hackforla/peopledepot#387]
### Dependencies
- [ ] PD has a feature to be released

### Overview
We need to drive the process for completing and releasing a feature so that:
- Progress towards completion can be secured and assessed, including the removal of obstacles
- Progress is visible to all stakeholders
- Progress can easily be reported to stakeholders

### Action Items
- [ ] Consider creating a consistent rule for renaming Issues on the PD project board, so it's immediately clear at the beginning of the issue name who needs to work on them. For example, 'Create...' (for Dev), 'Implement...' (for Dev), 'Design...' (for Design) 'Usability testing...' (for Research)
- [ ] Consider creating a series of ranking labels like the following (used by TDM) to be applied to issues in the Prioritized Backlog:
- `time sensitive` - issues with this label go to the top
- `priority: must have` - for MVP features
- `priority: should have` - for MVP features
- `priority: could have`
- `priority: won't have this time`
- [ ] On PD project board, create a new view formatted as a roadmap and with filters similar to [this example from the TDM project board](https://github.com/orgs/hackforla/projects/68/views/10), including some variation of `is:open` `label:"p-feature: My Projects Page"` `"p-feature: My Project Page-Admin view"` `"p-feature: Admin Tools"` `label:"priority: MUST HAVE"` `-label:"p-feature: snapshot"`
- [ ] When plotting the end dates for issues, remember that an issue with the label `size: 1pt` should represent about one week's work for a developer
- [ ] Do a regular audit of the whole [PD project board filtered for unassigned issues](https://github.com/orgs/hackforla/projects/61/views/1?filterQuery=is%3Aissue+is%3Aopen+no%3Aassignee), 
  - [ ] Is there a reason why they can't be worked on? Reach out to someone holding the relevant `role: ` and ask
  - [ ] Assign issue(s) if there's no reason why they can't be worked on
- [ ] Do a regular audit of issues in the Ice Box, as per #386, to see if any dependencies have been released and those issues can be put into the Prioritized Backlog: 

### Resources/Instructions
- [TDM roadmap](https://github.com/orgs/hackforla/projects/68/views/10)
- [PD project board filtered for unassigned issues](https://github.com/orgs/hackforla/projects/61/views/1?filterQuery=is%3Aissue+is%3Aopen+no%3Aassignee)
- https://github.com/hackforla/peopledepot/issues/386 
- See https://github.com/orgs/hackforla/projects/68/views/1?filterQuery=1719&pane=issue&itemId=67053828 for TDM's Google Sheet which has enabled them to make sure that features are being worked on by Dev and/or Design
