### ISSUE TITLE
Update milestones and create related PD: Roadmap

### ISSUE THREAD

**Issue by shmonks** [hackforla/peopledepot#397]
### Overview

We need to create a roadmap that includes the milestone list to help with: 
- Prioritization
- Project monitoring
- Team members' awareness of what tasks/issues build towards
- Synchronization across the organization, enabling cross-project collaboration

The roadmap will serve as a record of our milestones, their objectives, typical deliverables/outputs, and feature labels. 

### Action Items

- [ ] Create PD: Roadmap in Google Drive, cross-referencing with examples from OCS and Guides teams below
- [ ] Revise or add milestones deployed on PD repo, cross-referencing with PD: Roadmap sheet
- [ ] Paste link to PD: Roadmap in Resources/Instructions below

### Resources/Instructions

[PD: Roadmap](https://docs.google.com/spreadsheets/d/1vrvUvOSxKPhP06wlrA9pRt-3fNBLVYUCJnIvXrqdy1M/edit?gid=617281993#gid=617281993)
[Milestones on PD repo](https://github.com/hackforla/peopledepot/milestones)
- Creating a roadmap:
  - https://github.com/hackforla/guides/issues/36
  - https://github.com/hackforla/open-community-survey/issues/43
- Examples of roadmaps:
  - [OCS: Roadmap](https://docs.google.com/spreadsheets/d/163RPNWPhkeah2OvGCqjByMukYduXk66XY7ZpcpLCzXU/edit#gid=617281993)
  -  [Guides: Roadmap](https://docs.google.com/spreadsheets/d/1xYUlIKsfE2-CeExIQ8i3oLD8pC7hjMTPM2YLSMFA8_s/edit#gid=0)
- Examples of milestones:
  - [OCS milestones](https://github.com/hackforla/open-community-survey/milestones?direction=asc&sort=title&state=open)
  - [Guides milestones](https://github.com/hackforla/guides/milestones?direction=asc&sort=title&state=open)

### Additional Resources

- [Milestone management](https://github.com/hackforla/open-community-survey/issues/77), this issue is an epic of audits for each milestone to confirm we have made all the necessary issues in order to deliver it.
  - Example of one of the issues under this epic [Milestone Check: 06 w1 requirements](https://github.com/hackforla/open-community-survey/issues/78)

**Comment by shmonks** [comment]
Checked 2025-01-23 and it seems fine for now.
