### ISSUE TITLE
Create Table: project_url

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#41]
### Dependencies
- #289 

### Overview

We need to create the project_url table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] add issue link to [the tables tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
- [x] identify and document table description (see spreadsheet under Resources)
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint
- Check to see if open issues in `FK status` below
   - [ ] If all Issues listed are closed (or there are no FKs), then skip the next 3 steps
      - [ ] comment out the code after you create it (see FK Status below for open/closed state)
      - [ ] add an action item on the open issue to uncomment the code line you commented out when that issue's table is created. 
      - [ ] Provide your file and line number as a permalink under resources in that issue

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Collection of URLs for a project by url type

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

Name | Type | FK Table | FK table Issue(s)
-- | -- | -- | --
project | int | project  | #16 
url_type| int | url_type | #77 
name | CharField(max_length=255) |  | 
externalid | CharField(max_length=255) |  | 
url | url varchar |  | 
url_status_type | int | url_status_type | #384 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables
   - #16 
   - #77 
   - #384 

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] project (many-to-one) #16 
   - [x] url_type (many-to-one) #77 
   - [x] url_status_type (many-to-one) #384 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by joshuayhwu** [comment]
```

class Project_URL(AbstractBaseModel):
	"""
	project_url
	"""
	id = models.IntegerField(primary_key=True)
	project_Id = models.ForeignKey(Project, on_delete=models.CASCADE)
	url_type_id = models.ForeignKey(Project, on_delete=models.CASCADE)
	url = models.URLField(blank=True) 

	def __str__(self): 
		return f"{self.name}" 

```

**Comment by fyliu** [comment]
This is better done after #77 since it references that table.
