### ISSUE TITLE
Update Table: User

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/peopledepot#429]
### Overview
We need to update the User table model to include new fields and have the correct names for fields.

#### Details
- The initial model issue: #15

### Action Items
Update existing Django model
- [x] Uncomment the referred_by field in the User model once the referrer table is created: https://github.com/hackforla/peopledepot/blob/b97453e67147c4bf1ccc210ff50d76282df812b5/app/core/models.py#L90
- [x] In the files indicated by Resource 1.01, Change the following items in the code 

Current name in code | Updated Name | Updated Type (may already be this type) | FK Table | FK Issues
-- | -- | -- | -- | --
current_job_title | job_title_current_intake | varchar | | 
~~email~~ | ~~email_intake~~ | EmailField | | 
~~first_name~~ | ~~name_first~~ | varchar | | 
gmail | email_gmail | EmailField | | 
~~is_active~~ | user_status_id | int | user_status_type | #35
~~last_name~~ | ~~name_last~~ | varchar | | 
preferred_email | email_preferred | EmailField | | 
target_job_title | job_title_target_intake | varchar | | 

- [x] Add the following items in the code
- [ ] 

Name | Type | FK Table | FK table Issue(s)
-- | -- | -- | --
practice_area_primary | int (practice_area_primary) | practice_area | #63
practice_area_secondary | int[] (practice_area_secondary) | practice_area | #63
practice_area_target_intake | int[] (practice_area_target_intake) | practice_area | #63
~~referred_by~~ referrer | int | referrer | #68
email_cognito | EmailField | | 

- [x] Write a test for the new relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project) if any.
- [x] Update API end point
- [x] Update API unit tests
- [x] [generate a schema table definition](https://github.com/hackforla/peopledepot/issues/378#issuecomment-2493062821) and post it in a comment below and add a link to it in the Update Schema dependency issue.
- [x] For each of the FK Above if the FK table has not yet been created (i.e, the issue is still open), you will need to
   - comment out the code after you create it 
   - add an action item on the open issue to uncomment the code line you commented out when that issue's table is created. 
   - Provide your file and line number as a permalink under resources in that issue
- [ ] Document the endpoint in ReDocs

### After PR has been approved
- [ ] Release the dependency and move the issue out of the icebox for #436

### Resources
- 1.01 Code locations
   - 1.01.01 [/app/core/models.py](https://github.com/hackforla/peopledepot/blob/main/app/core/models.py)
   - 1.01.02 [/app/core/admin.py](https://github.com/hackforla/peopledepot/blob/main/app/core/admin.py)
   - 1.01.03 [/app/core/api/serializers.py](https://github.com/hackforla/peopledepot/blob/main/app/core/api/serializers.py)
   - 1.01.04 [/app/core/migrations/0002_user_current_job_title_user_current_skills_and_more.py](https://github.com/hackforla/peopledepot/blob/main/app/core/migrations/0002_user_current_job_title_user_current_skills_and_more.py)
- 1.02 [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- 1.03 [Spreadsheet, User view filter](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=371053454#gid=371053454&fvid=139862014)

#### FK status
- #35
- #63 
- #68

**Comment by fyliu** [comment]
![User](https://github.com/user-attachments/assets/2905f2c9-6768-4a82-b58a-73a201f94335)

**Comment by shmonks** [comment]
@Neecolaa and @ExperimentsInHonesty to review current column fields

**Comment by shmonks** [comment]
We need to add a Cognito email field in this table

**Comment by fyliu** [comment]
@Neecolaa It might not be part of this issue, but can we **add descriptions** to all the columns to help developers using the API figure out how they should use them? Something like this example I made up?

I bolded the target column names to make them more noticeable.

I think the developer should also **generate and post a schema image** of the table like I did above but in the PR.

Current name in code | Updated Name | Updated Type (may already be this type) | description
-- | -- | -- | --
first_name | **name_first** | varchar | User's first name
last_name | **name_last** | varchar | User's last name
created_date | **created_at** | DateTimeField | Auto-generated date and time when user was created
is_active | **user_status_id** | int | User active status. This is determined by <...>
current_job_title | **intake_job_title_current** | varchar | The job title when first joined the organization. This is not updateable by the user later.
target_job_title | **intake_job_title_target** | varchar | The user's target job title when first joined the organization. This is not updateable by the user later.

The description would show up in the API docs like the "Event name" in this example:
![2024-11-15 15 50 45 localhost 58e8d85425ba](https://github.com/user-attachments/assets/0b0dfa4d-d7fb-4f86-b0bd-a6329ed4dfe2)

**Comment by ExperimentsInHonesty** [comment]
@fyliu @ethanstrominger Do you know what are these fields for: 
is_staff
is_superuser

Re the comment above about putting descriptions.  We will do that on another epic, once we get all the table changes with the correct field names made.

**Comment by fyliu** [comment]
@ExperimentsInHonesty Those are what django uses in the default model. See [link to reference](https://docs.djangoproject.com/en/5.1/ref/contrib/auth/#django.contrib.auth.models.User.is_staff).

is_staff:
  - Boolean. Allows this user to access the admin site.

is_superuser:
  - Boolean. Treats this user as having all permissions without assigning any permission to it in particular.

`is_staff` currently has a description in peopledepot that we can update: "Designates whether the user can log into this admin site."

---

I said there's no way to get the text-only description before. But I forgot about just **asking the database** for it. Maybe the developer making the change can do a before and after output of this? I can provide this for the other tables as well.

Here's what the **`user` table is defined** as in the database currently:
<details>
  <summary>click to expand</summary>

```
                           Table "public.core_user"
      Column       |           Type           | Collation | Nullable | Default 
-------------------+--------------------------+-----------+----------+---------
 password          | character varying(128)   |           | not null | 
 last_login        | timestamp with time zone |           |          | 
 is_superuser      | boolean                  |           | not null | 
 uuid              | uuid                     |           | not null | 
 created_at        | timestamp with time zone |           | not null | 
 updated_at        | timestamp with time zone |           | not null | 
 username          | character varying(255)   |           | not null | 
 is_active         | boolean                  |           | not null | 
 email             | character varying(254)   |           | not null | 
 is_staff          | boolean                  |           | not null | 
 current_job_title | character varying(255)   |           | not null | 
 current_skills    | character varying(255)   |           | not null | 
 first_name        | character varying(255)   |           | not null | 
 github_handle     | character varying(255)   |           | not null | 
 gmail             | character varying(254)   |           | not null | 
 last_name         | character varying(255)   |           | not null | 
 linkedin_account  | character varying(255)   |           | not null | 
 phone             | character varying(128)   |           | not null | 
 preferred_email   | character varying(254)   |           | not null | 
 slack_id          | character varying(11)    |           | not null | 
 target_job_title  | character varying(255)   |           | not null | 
 target_skills     | character varying(255)   |           | not null | 
 texting_ok        | boolean                  |           | not null | 
 time_zone         | character varying(63)    |           | not null | 
Indexes:
    "core_user_pkey" PRIMARY KEY, btree (uuid)
    "core_user_username_36e4f7f7_like" btree (username varchar_pattern_ops)
    "core_user_username_key" UNIQUE CONSTRAINT, btree (username)
Referenced by:
    TABLE "core_user_groups" CONSTRAINT "core_user_groups_user_id_70b4d9b8_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_user_user_permissions" CONSTRAINT "core_user_user_permissions_user_id_085123d3_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_userpermission" CONSTRAINT "core_userpermission_user_id_2b95370e_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "django_admin_log" CONSTRAINT "django_admin_log_user_id_c564eba6_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
```
</details>

The **steps** to get this are below:
<details>
  <summary>click to expand</summary>

- How to get the database table definition

    ```
    # run this to enter the database in the docker container
    ./scripts/db.sh

    # within the database

    # get the list of tables
    # "describe tables"?
    \dt

    # get the details of a table
    # "describe table"?
    \d core_user
    ```

    ```
    # or as one command:
    ./scripts/db.sh -c "\d core_user"

    # get all the table names
    ./scripts/db.sh -c "\dt"
    ```

</details>

**Comment by fyliu** [comment]
@ethan pointed out that `is_staff` and `is_superuser` are internal data and don't need to be exposed to the API client. They can find out who the adminGlobals are from the `user_permission` rather than the `user` table.

**Comment by ExperimentsInHonesty** [comment]
@del9ra We updated the action items to include 
- FK Issue numbers.  All of those issues are closed (i.e., the FK tables have been created) except 
   - https://github.com/hackforla/peopledepot/issues/68.
- Instructions on what to do on the line of code that references the FK where the table is not yet created (table: referrer)

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by fyliu** [comment]
I would like to confirm a few things that'll help in writing tests for this:

normal usage:
1. `user` object starts out nearly blank. "created" by cognito login process: `email_cognito`, `id`, `password`
1. user fills out form: 
   - text: `name_first`, `name_last`
   - email: `email_gmail`, `email_preferred`, `email_intake`
   - text: `job_title_current_intake`, `job_title_target_intake`
   - choice: `practice area_primary`, `practice area_secondary`, `practice area_target_intake`
1. admin assign:
   - choice: `referred_by`, `user_status_id`

**Comment by del9ra** [comment]
Last week, I updated the user model, renamed variables across multiple files, and resolved system check errors. I fixed a duplicate user_status_id issue by assigning unique related names and addressed an email field problem by modifying UserManager.

I also tackled merge conflicts in migrations and wrote tests for one model’s relationships. Next, I’ll test another relationship and generate a schema table.
ETA: March 20

**Comment by del9ra** [comment]
```
Table "public.core_user"
          Column          |           Type           | Collation | Nullable | Default 
--------------------------+--------------------------+-----------+----------+---------
 password                 | character varying(128)   |           | not null | 
 last_login               | timestamp with time zone |           |          | 
 is_superuser             | boolean                  |           | not null | 
 uuid                     | uuid                     |           | not null | 
 created_at               | timestamp with time zone |           | not null | 
 updated_at               | timestamp with time zone |           | not null | 
 username                 | character varying(255)   |           | not null | 
 email_intake             | character varying(254)   |           | not null | 
 is_staff                 | boolean                  |           | not null | 
 job_title_current_intake | character varying(255)   |           | not null | 
 current_skills           | character varying(255)   |           | not null | 
 name_first               | character varying(255)   |           | not null | 
 github_handle            | character varying(255)   |           | not null | 
 email_gmail              | character varying(254)   |           | not null | 
 name_last                | character varying(255)   |           | not null | 
 linkedin_account         | character varying(255)   |           | not null | 
 phone                    | character varying(128)   |           | not null | 
 email_preferred          | character varying(254)   |           | not null | 
 slack_id                 | character varying(11)    |           | not null | 
 job_title_target_intake  | character varying(255)   |           | not null | 
 target_skills            | character varying(255)   |           | not null | 
 texting_ok               | boolean                  |           | not null | 
 time_zone                | character varying(63)    |           | not null | 
 user_status_id           | uuid                     |           |          | 
 email_cognito            | character varying(254)   |           | not null | 
Indexes:
    "core_user_pkey" PRIMARY KEY, btree (uuid)
    "core_user_user_status_id_ce918f08" btree (user_status_id)
    "core_user_username_36e4f7f7_like" btree (username varchar_pattern_ops)
    "core_user_username_key" UNIQUE CONSTRAINT, btree (username)
Foreign-key constraints:
    "core_user_user_status_id_ce918f08_fk_core_userstatustype_uuid" FOREIGN KEY (user_status_id) REFERENCES core_userstatustype(uuid) DEFERRABLE INITIALLY DEFERRED
Referenced by:
    TABLE "core_user_groups" CONSTRAINT "core_user_groups_user_id_70b4d9b8_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_user_practice_area_secondary" CONSTRAINT "core_user_practice_a_user_id_66be93c6_fk_core_user" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_user_practice_area_target_intake" CONSTRAINT "core_user_practice_a_user_id_8fb02461_fk_core_user" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_user_practice_area_primary" CONSTRAINT "core_user_practice_a_user_id_a932120a_fk_core_user" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_user_user_permissions" CONSTRAINT "core_user_user_permissions_user_id_085123d3_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "core_userpermission" CONSTRAINT "core_userpermission_user_id_2b95370e_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
    TABLE "django_admin_log" CONSTRAINT "django_admin_log_user_id_c564eba6_fk_core_user_uuid" FOREIGN KEY (user_id) REFERENCES core_user(uuid) DEFERRABLE INITIALLY DEFERRED
```

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by ExperimentsInHonesty** [comment]
- Since issue #68 is still open 
  - [ ] comment out the code after you create it
      - [ ] add an action item on #68 to uncomment the code line you commented out in this pr when that issue's table is created. 
      - [ ] Provide your file and line number as a permalink under resources in that issue

**Comment by vanessaavviles** [comment]
Please provide update

Progress: "What is the current status of your project? What have you completed and what is left to do?"

Blockers: "Difficulties or errors encountered."

Availability: "How much time will you have this week to work on this issue?"

ETA: "When do you expect this issue to be completed?"

Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

remember to add links to the top of the issue if they are going to be needed again.
