### ISSUE TITLE
Epic: Update all issues with instructions about adding a slide to the staging deck

### ISSUE THREAD

**Issue by shmonks** [hackforla/peopledepot#444]
### Overview
The staging deck is where we will create slides relating to any issue which is currently In Progress AND relates to our stakeholders.

Every issue on the PeopleDepot project board needs to contains instructions for updating the staging deck, so that: 
- We can reduce the time it takes to make the staging deck, and 
- We don't miss issues that are relevant to our stakeholders.

### Action Items
- [ ] Create the following issues:
  - [ ] https://github.com/hackforla/tdm-calculator/issues/1968
  - [ ] https://github.com/hackforla/tdm-calculator/issues/1970
  - [ ] https://github.com/hackforla/tdm-calculator/issues/1971
  - [ ] https://github.com/hackforla/tdm-calculator/issues/1972
  - [ ] https://github.com/hackforla/tdm-calculator/issues/1973

- [ ] Add the appropriate labels to each issue (see 1968), including `ready for prioritization`
- [ ] Add the milestone `05. Team Workflow` to each issue

#### Sections 
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

```
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.

### Action Items

- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Add the text from template to each
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Resources
- [PeopleDepot project board, In Progress]
- [Project Board, Prioritized Backlog]
- [TDM staging deck](https://docs.google.com/presentation/d/1crZ3IxqA4hAu3qzD7ns93Ieuqjwh6wyEtuX_46cP-fg/edit#slide=id.g1443c52839c_0_2)
- PeopleDepot staging deck to be added

#### Sections of the staging deck
- Discussion Topics (product or research)
- Design Review (design)
- Updates to Review & Release (dev)

### Template
```
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
   - [ ] If no slide has been made, make one in the PeopleDepot staging deck
- [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
```

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Template
    ````
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
    ````

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Template
    ```
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
    ```

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Template
    ```
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
    ```

**Comment by shmonks** [comment]
```
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
- [ ] If no slide has been made, make one in the PeopleDepot staging deck
- [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
```

**Comment by shmonks** [comment]
- [ ] Review with product and dev. Update if needed based on feedback
- [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
- [ ] If no slide has been made, make one in the PeopleDepot staging deck
- [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Template
    ```
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
    ```

**Comment by shmonks** [comment]
Please provide update
1. Progress: I still need to create the staging deck
2. Blockers: I need help with the markdown above: how to create a template within a template?!
3. Availability: Tomorrow
4. ETA: Next week
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

### Template
    ````
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck.
    ````

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the column
- [ ] Open all the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in the staging deck
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

    ````
    - [ ] Review with product and dev. Update if needed based on feedback
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in the PeopleDepot staging deck
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck
    ````

**Comment by shmonks** [comment]
### Overview
Update the issues in the [NAME OF COLUMN] with the staging deck links so that we can reduce the time it takes to make the staging deck every week, and so that we don't miss issues.
### Action Items
- [ ] Go to the relevant column using this link: [ADD LINK FROM #444, Resources 1.02]
- [ ] Open each of the issues in the column
- [ ] Copy the template below into the top comment of each issue
- [ ] Check to see if there is a slide in [the PeopleDepot staging deck](https://docs.google.com/presentation/d/1oyt89K7cPuvhf72OdfJMGZi4KyZqUv7VAwXLNW-we_w/edit#slide=id.g1443c52839c_0_324)
   - [ ] if not, create a slide in the appropriate section
- [ ] Customize the issue with the URL from the deck 

    ````
    - [ ] Review with Product and Dev, and update if needed
    - [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
    - [ ] If no slide has been made, make one in [the PeopleDepot staging deck](https://docs.google.com/presentation/d/1oyt89K7cPuvhf72OdfJMGZi4KyZqUv7VAwXLNW-we_w/edit#slide=id.g1443c52839c_0_324)
    - [ ] Get stakeholder sign-off via the stakeholder meeting slide deck
    ````

**Comment by shmonks** [comment]
- [ ] Review with Product and Dev, and update if needed
- [ ] Once finalized, add before and after images to the staging deck on this slide (link to be added) 
- [ ] If no slide has been made, make one in [the PeopleDepot staging deck](https://docs.google.com/presentation/d/1oyt89K7cPuvhf72OdfJMGZi4KyZqUv7VAwXLNW-we_w/edit#slide=id.g1443c52839c_0_324)
- [ ] Get stakeholder sign-off via the stakeholder meeting slide deck
