### ISSUE TITLE
Create Table: project_status (used to say project_program_area_status)

### ISSUE THREAD

**Issue by Neecolaa** [hackforla/peopledepot#46]
### Overview

We need to create the project_status table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] add issue link to [the tables tab of the spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=1228509670)
- [x] identify and document table description (see spreadsheet under Resources)
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [x] ~~Create issue for updating `project`table connecting `current_status_id` to `project_status`~~
-- This was done in the PR attached to this issue instead of creating a new one. 
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint

### Post issue tasks

- [ ] resolve dependency on #67 and move it from Ice Box to New Issue Review with `ready for tech lead` label

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of status options for project and program_area

### Data Fields

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] (PK) id - int - Record Id
   - [x] name - varchar
   - [x] description - varchar

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] project (one-to-many) #16
   - [x] project_status_history (one-to-many) #67 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by ExperimentsInHonesty** [comment]
remove program area from this table.  It should be projects only

**Comment by Neecolaa** [comment]
DB Architect to-do:
Change name from `project_program_area_status` to `project_status`

- [ ] In tables tab
   - [ ] table name
   - [ ] table connections
- [ ] In fields tab
- [ ] In associated tables' issues
- [ ] In ERD

**Comment by Neecolaa** [comment]
DB Architect to-do:

 - [ ] Remove `status_id` in `program_area`
    - [ ] in fields tab
    - [ ] in ERD
    - [ ] create update issue for `program_area` to remove `status_id`
- [ ] Remove table connection between `project_status` and `program_area`
    - [ ] in table tab
    - [ ] in ERD

**Comment by fyliu** [comment]
Need to have initial data in the [spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?pli=1&gid=1572339087#gid=1572339087) for `project_status` table

**Comment by ExperimentsInHonesty** [comment]
Initial data is
Active
On Hold
Completed
Closed


There is also another bit of information and I don't know exactly where it goes right at this min. But it's a visible: hidden.  That is in addition to the status above.  e.g., a project that is on-hold and hidden would not show up on the website.  This is probably on the project table.

**Comment by dmartin4820** [comment]
Progress: Got my branch setup locally with minor changes. 
    Blockers: None so far.
    Availability: Should have time this weekend, and potentially time in the evenings (i.e. 7pm to 9pm).
    ETA: Early next week or end of this weekend.

**Comment by fyliu** [comment]
> * [ ] The issue description says that the program_area model should have a relationship with the project_status model. The [row in the PD: Table and field explanations Google sheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=1228509670#gid=1228509670&range=23:23) doesn't list this relationship (the[ Lucidchart diagram](https://lucid.app/lucidchart/ac2f3e81-00d2-4257-b1fc-266d7f0a4cbe/view?page=0_0#) doesn't indicate a relationship either). Which is correct?

I would ask @Neecolaa since it has to do with the database design and since she created this issue and made the change I refer to in the next sentence. From the issue history, it looks like the original issue had to do with project and program_area, and then this line was inadvertently left over when the issue was changed to project_status.

> * [ ] The issue also requires me to create another issue to update the `current_status_id` foreign key field to project_status. It should be possible to do this with the PR that I make for this issue by removing the line [here](https://github.com/dmartin4820/peopledepot/blob/main/app/core/models.py#L140). Should I still create an issue, or make the change I suggest in the PR for this issue?

You're right. It's easier to just do that in this issue. Please update that task to do that.

**Comment by Neecolaa** [comment]
Fang's correct: when I updated the ERD and spreadsheet I neglected to remove the connection from this issue as well. I've done that now. Thank you for double checking that!

**Comment by dmartin4820** [comment]
1. Progress: [Got comments from Del on the PR](https://github.com/hackforla/peopledepot/pull/449#pullrequestreview-2471044282). The first change suggested by Del is easy to do.
2. Blockers: The second change is addressed in [the response to Del's comment](https://github.com/hackforla/peopledepot/pull/449#issuecomment-2579113188). To summarize, the table created for the PR has seed data that doesn't include an ID (UUID) column, but we may want to modify it to maintain consistency with existing tables, pending Fang and/or Nicole's response.
3. Availability: Will not be able to make the meeting on 1/9/2025, but I will be able to work on this weekend.
4. ETA: By next Tuesday assuming no blockers.
5. Pictures: N/A

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by dmartin4820** [comment]
1. Progress: I made the update that Del suggested for the initial data. 
2. Blockers: Will ask about the UUID issue in the meeting.
3. Availability: Weekend 
4. ETA: Weekend
5. Pictures or links* (if necessary): N/A

**Comment by dmartin4820** [comment]
1. Progress: Got review from Del. Need to rebase main into my PR branch.
2. Blockers: n/a
3. Availability: Friday/Weekend
4. ETA: Saturday

I'll also pick up another task over the weekend.

**Comment by dmartin4820** [comment]
1. Progress: Got review from Fang and made the changes.
2. Blockers: n/a
3. Availability: Friday/Weekend
4. ETA: N/A. Done.
