### ISSUE TITLE
Create Table: soc_detailed

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#73]
### Overview

We need to create the soc_detailed table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] add seed data
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint
- Check to see if open issues in `FK status` below
   - [ ] If all Issues listed are closed (or there are no FKs), then skip the next 3 steps
      - [ ] comment out the code after you create it (see FK Status below for open/closed state)
      - [ ] add an action item on the open issue to uncomment the code line you commented out when that issue's table is created. 
      - [ ] Provide your file and line number as a permalink under resources in that issue

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Dictionary of SOC (Standard Occupational Classification) detailed occupations. The data can be found in the [PD Spreadsheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit#gid=2143059131).

### Data Fields
Name | Type | FK Table | FK table Issue(s)
-- | -- | -- | --
soc_broad | int | soc_broad | #72 
occ_code | varchar |  | 
title | varchar |  | 
description | textfield |  | 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### FK status
- #72 

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] soc_broad (many-to-one) #72 
   - [x] user_employment_change (one-to-many) #81 
   - [x] modern_job_title (one-to-many) #62 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by fyliu** [comment]
Problems:
1. Missing description
   1. I added it but need to verify it's good 
1. Missing associated tables in spreadsheet
   1. I added them

**Comment by shmonks** [comment]
@fyliu Is this issue's dependency on #72 simply because it contains the FK used in the 'soc_detailed' table? If so, I will edit this to give instructions on dealing with FKs when the other table has not yet been created, and move into New Issue Review.

**Comment by fyliu** [comment]
> [@fyliu](https://github.com/fyliu) Is this issue's dependency on [#72](https://github.com/hackforla/peopledepot/issues/72) simply because it contains the FK used in the 'soc_detailed' table?

Yes. That's the only reason.

**Comment by shmonks** [comment]
@Neecolaa I suspect there's been a mistake in listing this table's associated tables in the [PD: Tables and fields sheet](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=1228509670#gid=1228509670&range=E37) - it lists 'modern_job_title (one-to-many)' twice and doesn't list 'soc_broad (many to one)'. Could you correct if necessary? Thanks

**Comment by Neecolaa** [comment]
It's been corrected, thank you for pointing that out!
