### ISSUE TITLE
Create Table: user_check

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#80]
### Overview

We need to create the user_check table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [x] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [ ] create a single model in Django (defining schema)
- [ ] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [ ] write an API end point
- [ ] write API unit tests
- [ ] document the endpoint
- [ ] - Check to see if open issues in `FK status` below
   - [ ] If all Issues listed are closed (or there are no FKs), then skip the next 3 steps
      - [ ] comment out the code after you create it (see FK Status below for open/closed state)
      - [ ] add an action item on the open issue to uncomment the code line you commented out when that issue's table is created. 
      - [ ] Provide your file and line number as a permalink under resources in that issue

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

- holds checks that are asked of users (Accepted Code of Conduct, Github membership public, Google Calender invite Accepted, ...)

### Data Fields

- [ ] For each FK below: if the FK table has not yet been created (i.e, if the issue for it under **Associated Tables** below is still open), you will need to
   - [ ] Comment out the code after you create it 
   - [ ] Add an action item on the open issue to uncomment the code line you commented out when that issue's table is created. 
   - [ ] Provide your file and line number as a permalink under resources in that issue

Name | Type | FK Table | FK table Issue(s)
-- | -- | -- | --
user | int | user  | #15
org  | int | org | #56
project | int | project | #16
check_type  | int | check_type | #59
result | Boolean |  | 
reminder_start | DateTimeField |  | 
completed_at | DateTimeField  |   | 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### FK status
- #15
- #16
- #56
- #59
### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   - [x] check_type (many-to-one) #59 
   - [x] organization (many-to-one) #56 
   - [x] user (many-to-one) #15 

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - project (many-to-one) #16

**Comment by fyliu** [comment]
Problems:

1. Missing description
1. Missing table association in spreadsheet
   1. I added the table and join type to the spreadsheet.

**Comment by ExperimentsInHonesty** [comment]
@Neecolaa Please review and see if we are ready to proceed with making this table.

**Comment by Neecolaa** [comment]
Updated brigade to organization, still need to check project connection before releasing issue.
