### ISSUE TITLE
Create Table: win

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#82]
### Overview

We need to create the win table so that we can update a shared data store across hackforla.org, vrms, civictechjobs, and tables (onboarding) project.

#### Details

A table and a model are the same thing

### Action Items

- [x] identify and document table description (see spreadsheet under Resources)
  - [ ] if not, reach out to PD leads
- [x] compare and check off the data fields (below) against the ERD. Note any fields in the ERD that's missing from the list. (see Resources)
- [x] compare the check off associated tables (below) against the ERD. Note any associated tables in the ERD that's missing from the list (see Resources)
- [x] create a single model in Django (defining schema)
- [x] write a test for the relationships this model will have with other models (e.g., creating a user and assigning them a set of permissions on a project).
- [x] write an API end point
- [x] write API unit tests
- [x] document the endpoint
- Check to see if open issues in `FK status` below
   - [ ] If all Issues listed are closed (or there are no FKs), then skip the next 3 steps
      - [ ] ~comment out the code after you create it (see FK Status below for open/closed state)~
      - [ ] ~add an action item on the open issue to uncomment the code line you commented out when that issue's table is created.~
      - [ ] ~Provide your file and line number as a permalink under resources in that issue~

### Resources/Instructions

- See [People Depot Resources wiki page](https://github.com/hackforla/peopledepot/wiki/Resources-and-Links) for links
  - ERD
  - Table and Field Definitions
  - API Endpoint
- See the [wiki page](https://github.com/hackforla/peopledepot/wiki/Create-Table-issues-data-gathering-workflow) for instructions.

### Description

Connects a win to a user

### Data Fields

- [ ] For each FK below: if the FK table has not yet been created (i.e, if the issue for it under **Associated Tables** below is still open), you will need to
   - [ ] ~Comment out the code after you create it~ 
   - [ ] ~Add an action item on the open issue to uncomment the code line you commented out when that issue's table is created.~ 
   - [ ] ~Provide your file and line number as a permalink under resources in that issue~

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)

Name | Type | FK Table | FK table Issue(s)
-- | -- | -- | --
user |  int | user | https://github.com/hackforla/peopledepot/issues/15
practice_areas  |   int[] (practice_area id)  |    |  
teams  |  int[] (projectID)  |    |  
description  |  varchar  |    |  
win_type |  int  |  win_type | https://github.com/hackforla/peopledepot/issues/61
can_use_photo  |  boolean   |    |  

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

### FK status
- #61 

### Associated Tables

1. Copied from spreadsheet and checked off according to ERD. (unchecked items indicate a mismatch between ERD and spreadsheet, which requires a review)
   1. FK tables
   - [x] win_type (many-to-one) #61 
   - [x] user (many-to-one) #15 
   1. tables where FKs are used but because its an array, it won't throw an error if the table is not there.
   - [x] practice_area (many-to-many array of ids) #63
   - [x] project (many-to-many array of ids) #16

1. In ERD only (having items here indicates a mismatch, which requires a review)
   - None

**Comment by joshuayhwu** [comment]
```
class Win(AbstractBaseModel):
	"""
	win
	"""
	id = models.IntegerField(primary_key=True)
	user_int = models.ForeignKey(User, on_delete=models.CASCADE)
	roles = models.ForeignKey(Role, on_delete=models.CASCADE)
	teams = models.ForeignKey(Project, User, on_delete=models.CASCADE)
	description = models.CharField(max_length=255)
	accomplishment_type = models.ForeignKey(Accomplishment, on_delete=models.CASCADE)
	can_use_photo = models.BooleanField()

	def __str__(self): 
		return f"{self.name}" 

`````

**Comment by Neecolaa** [comment]
ERD/SS To-do:
replace roles (int array of role_ids) with practice_areas (int array of practice_area ids)
- [ ] on the ERD
- [ ] on the fields tab of the spreadsheet

remove relationship between role and win tables
- [ ] on the ERD
- [ ] on the spreadsheet
- [ ] on this issue

add relationship between practice_area and win tables
- [ ] on the ERD
- [ ] on the spreadsheet
- [ ] on this issue

Discussion for these changes happened here: https://github.com/hackforla/peopledepot/discussions/170

**Comment by Neecolaa** [comment]
#61 has changed names from accomplishment_type to win_type, so this issue's associated tables has been updated to reflect that. Likewise, the accomplishment_type field has been changed to win_type_id.

**Comment by shmonks** [comment]
@fyliu Is this issue's dependency on #61 simply because it contains the FK used in the 'win' table? If so, I will edit this to give instructions on dealing with FKs when the other table has not yet been created, and move into New Issue Review.

**Comment by fyliu** [comment]
> [@fyliu](https://github.com/fyliu) Is this issue's dependency on [#61](https://github.com/hackforla/peopledepot/issues/61) simply because it contains the FK used in the 'win' table?

Yes. That's the only reason.
