### ISSUE TITLE
Epic: Redesign event schema

### ISSUE THREAD

**Issue by fyliu** [hackforla/peopledepot#88]
### Dependency

 - #173 to rename `recurring_event` table to `event` and make simple changes first

### Overview
As database architects, we would like to make sure the schema is designed well and adhere to good relational design. The current event tables are modeled after the old VRMS non-relational database, and doesn't fit some normal use cases very well as well as having data duplication. We need to redesign it to be simpler, more useful, with no data duplication, and follow the iCalendar (not related to Apple) standard.

### Action Items

- [x] Research. Read through a few designs
- [x] Create a design that includes the use of the django-recurrence field
- Propose the design at a meeting
  - [x] discuss the pros/cons
  - [x] compare to the existing design
  - [x] present some scenarios where it does better
- new design related tasks
  - [x] write down the final table design here. Added to the issue description.
  - [x] modify the ERD
  - [x] modify the spreadsheet
  - [x] modify #173 to rename to `event`
  - [x] close #47 since we will rename `recurring_event` to it in #173

- [x] close #55 if we don't need it anymore
- [ ] review #57 and close if we don't need it anymore
- [x] #151
- [x] Revisit #55 to see if it's still relevant

### Resources/Instructions
- [rrule demo](https://jakubroztocil.github.io/rrule/)
- search for "data model for recurring calendar events"
- stackoverflow [answer](https://stackoverflow.com/a/38359184) - other answers could be useful as well
- iCalendar standard [RFC 5545](https://www.rfc-editor.org/rfc/rfc5545)
- Tim Shaker's [schema](https://github.com/tmshkr/vrms) is also worth referencing. It is modeled after google calendar

- Why it needs to be changed
   - it's unnecessarily complex
   - it only has weekly recurrence but no monthly like the CoP Leads meetings
   - each recurring event instance doesn't need to generate a new database record, unless there's design considerations for doing so
   - use the iCalendar standard rrule to define recurrence in a single field (replaces day_of_week, frequency_id (interval), fields missing(start_datetime, end_datetime, timezone, yearly, monthly, and more) 
   - unnecessary data duplication with location data fields. #55

### New Design

- It's mostly the same as the old one except the 3 core event tables are combined into one and the recurrences field is going to take care of the functionalities that were spread across the 3 tables. Some tables were dropped because the recurrences field also takes care of their functions.
- To edit the diagram, copy the link and replace `png` with `uml`.

![New Design](https://www.plantuml.com/plantuml/png/dLJDZjj63BxFKx2v-D0uG7DS1460jW62Ne8Yjs0XZ3MqnUveA70ekqvstxr3IPwrZNMBvY9p-7ty9_qXgnST--XM-O4I26Tqgv-qmnvXJnlnIUjx4qSSXCuqhUZQznkK2yrE45FLz5voVGpHKt9N_fsIHeHNduK7pXW0zvWK0cRQfLVEhI9k5PH1QDSLFGcsIfoSfJnuyJr4IgZ70O55EtQh5v21uz4UpfcvJxk8yFiKwBjp04KWFG8k6W20dodSmTvBstc1T-y-__7-_QoVI8rvROoou1yhddoFrN9M1Sojq61fNo7J19hW5Hibi_kjY5-Az94mXiLw56-c3QMcf-A1aiw8O3kAO6enty6VzJ7RpfGz1UIcvRJ52Mj6YNTGFZCSkPrzrsglgXc4_y9MR-ARCXOVy2Ly9lWGo2BuMFBVScKjS3zcROGZvefylR-8a3iUO_XtJliVb2S7a5WHb8SYVkae0sNG3g7bVaEfxbtF0QE30dajM59FQIO-Dxl0LehqK-l0fm2jB_eOJsxo6ollaq9Wp1OPyZWCB0gSS6sJddc5n7iKeO3vTU6q7VWC6LKfxS0NED1scfo23q4mPs2nyRsPjZPCLPrlS5tE6sly_zUqDc--mALzLZ5i4CeNqzXFzVxAgHHZgHT43uWpDZKeersaehNMRo9Q-mlv20FdJ4LHocUWBHoCSl1fkldfF82tMyZK3qOoXmxCsiEEEG1F-LwqetRZjDq_q8jw62zWooIQNsxetzxorPQaAlO9Ehz7kA9azLhYJGlyzluA_4R3bUkXuuHLTsFJf-kmOVK-80npIssd7Pnl_MlOZ6f9sG19pqTse1Z1nyW76BCDHd1B2Sq71Az-keXC0SjFm07B9vs2p25E1z7xesLoOD4E8lE31TkoWFd8wbFm4kWRXhhl5nVPsmhQpHONL3nucE-mu7iVANXbkTY59-TM-BUY91z1UQat7xDYxvOr6JFAIHQEU9AN_xxJS_whgsZROVlGK79kzhaEwyVlPmUug9yUrxAkctZYndNrlcZ6TGrmRYWSJmfxFWUrf8rZGP-rAy7ebVPeTqKMSMfkuhIU4Kwveo6xrH8Urbyx2W7JVJZBSZLvhz3udEtA4Zf7QjQhMRW4QsOtpIfm7MdvVT7e0wOmzl4V)

**Comment by fyliu** [comment]
The recurring event model need fixing.

   1. It does not adequately cover common recurring event cases. This problem is easily addressed by adding an rrule field and possibly a couple other fields.

      1. It covers only weekly recurrences, which is most of team meetings, except some that are 2nd Tuesdays, for example.

         ```text
         RRULE:FREQ=WEEKLY;BYDAY=WE
         ```

      1. It doesn't cover one-time events

         ```text
         RRULE:COUNT=1
         ```

      1. It doesn't cover weekly except first week of the month CoP events

         ```text
         RRULE:FREQ=MONTHLY;INTERVAL=1;BYDAY=2WE,3WE,4WE,5WE
         ```

      1. It doesn't cover monthly CoP leads events

         ```text
         RRULE:FREQ=MONTHLY;INTERVAL=1;BYDAY=1WE
         ```

      1. It doesn't cover biweekly alternating weekdays onboarding events

         ```text
         DTSTART[0]:20230221T122700Z
         RRULE[0]:FREQ=WEEKLY;INTERVAL=2;BYDAY=TU
         DTSTART[1]:20230227T122700Z
         RRULE[1]:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO
         ```

   1. [Rrule tool](https://jakubroztocil.github.io/rrule/)

   1. [Discussion of how to use rrule and friends](https://www.nylas.com/blog/calendar-events-rrules/)

   1. Question about event instance design: is there a strong reason for keeping record of each event instance for recurring events? Seems like a lot of duplication.

      - from the code: The backend generates any missing events for today every 30 minutes
      - events can be generated on the fly by the client instead of by the backend. [Example in javascript](https://stackoverflow.com/questions/49765112/rrule-weekly-for-three-weeks-then-one-week-not-repeat#49765385)
      - I haven't looked at VRMS design docs to see if there's other reasons like being able to add meeting notes for each event. This is the most compelling reason.

   1. Question: How badly do we want to allow having a single recurring event to happen Monday or Tuesday for alternating weeks? We can implement this using 2 rrules in one event. "Normal calendar apps like Google and Apple don't allow this, probably because not many people would use it. It's not a lot of work to do. It's not possible to do with a single one. [Example for 2 separate events in google calendar](https://stackoverflow.com/questions/69353006/rrule-for-semi-weekly-events)

**Comment by chelseybeck** [comment]
I think we can just use [django-recurrence](https://django-recurrence.readthedocs.io/en/latest/usage/getting_started.html#form-usage) to simplify this.

**Comment by fyliu** [comment]
@chelseybeck this looks like exactly what we need. It even handles multiples rrules, which would allow us to have a single event for the slightly complex onboarding schedule, which Google calendar doesn’t support.

**Comment by ExperimentsInHonesty** [comment]
eliminate recurring table because we are going to use django recurance

[old event tables ](www.plantuml.com/plantuml/png/xLT1Zzis4xtpLyoNYu7LvmBPuo980xJDfOUsG80U5Wk15aSMQufKXvGtRhB_lQHDYp9DhnUBjfVs8ejyJpF3nqSE_C4wJcxi5LlOZTH0nY9R_Czrs2DivOguTjDufKOSICvc6d9Btg-GJcRMXAYdcPwJdGQ3ubApB3vpqYc4Dpyf0RX5xK2WbMlzXh65mjQ1Cq1otVbvITWuQJGBrGwSU0zAQdIx0S6GwmnR5931g5qOC1O-vtgj47xO9_h2640s-PqXz000-CHhzBLI709uMBhTeSgwazOPsaqWG2N57MmvDHqdUFVkvn_Vlq_OGEOtdwa-vNmyuGYq3SaXB74Y9NGh1PgwCRf5GjrWFPAw0_z856KQ7hv-DWjNhfw8clUOvueSBWIXjVNRA_Xjmiiv6Y_QDOvrtFb20kF-zk42wGyv5EBiJLmBxh1sCgpcU__woRzzbAX4uecHeZYwxgLNM6gNKC9c999wNOVjpVUftSmLR0YvGn5oNaxNTDXiV2hF5NxvAsCKSXtnf_YhZKCFEMVwEFF9-mgKCHl_b1i4wQ0nsd6fBRWE8yie0MlKIA6EU6nw8r054dUHnGcXuQePrPxMakaXM-StaxN5lfY2q_zp-B_1uK71lytXpWpdzdO6EgD4SlNh71sHCr_7-PkRN-xWLny1VEAJYh-zkSdD7mjF1o15dOx2bODm_HXKkIDVQEpgi6sXfpr3Mf5SS_4SG_1TRThw4N5pYT8I_ZwYRdRbCCcKqO_XoQwRy0MsgXIthXw7m11bojLhekf77uECGZiLV_-Gbz-PKObhhEOb92w432lcog-vDHCnsIcxv_DZiC9m282Ggu3EtH_Cdpe0IquF2uUGZlgzt2mpyXDZaujdEnuTNFPlqPiLNwq8jp9cyO7ZSXIsZiMbD5o7LH0EYZSeOBK3FqCqAcIfh5JHPB1Nr5Fg8NzHNO7Ve58eudc_KjqBhzHhTqALfOtd8poFURZDEsOrMgHYn2G5oNLtHGly7DEquOY1rC6ASmSMTKfNqJ-pWQ5GFVR5Meutvski7HkyaXhhjy-1jnbutl6hGeElplfvDNH6fp8kRrQuUCBAUouG1auEJ1jRvMnp_W-hqK77jzw381rOzDJ3VZvAfO0hPHvXtDyoXAtK6684Pt5FaTfAWVv7u83-eOz98FRGcTp-FbdWPuUakG9dOX5sPntsBEv4SEJndOp2utkq_t4OMrGS7ffoBJLZURTTgkNNBuTCbx7qLumL8b1Y1RUM2EaoAd-UNmfdhAUldZVPi1naVWUN69D69ImALavyK9f5jbXccang9PtZr9GpST8Ys4cK4oo7KXoMb9eALCkzBSfG-d8HI64oQ9KSiI1KFkaMOJ1MXkpG6W9jzFA066qxELYsoEClxpif1Ee7aVHRn9SJCEt-nH3BkOCMiUO4vveNAKc-uyiyVcwncLiIRHPZAlhbwDo0GUo4ZJFt6OKp84btfjmuCzG7r6BirPy0)


[new event ](www.plantuml.com/plantuml/png/dLHBZzis4BxpLqnpyQ5HWEOO1460jW62NdB8BLW8j3YsfajnXE78ZfFiVoz73-rQMBTe05iYls_U3xtFwaM7BhfTlgS4mXdTxXTjiKCuqLvyqlM-ZmFsGa-GHhJotHxb2ZaAObgHpajUBttqbDp6lbFIYF3Yat3F6GFW2PD2m4p7zCAvNSI3WZ887Tk2as2ZnCbPoBqNtq6aX7hf4LYqPRTxXkavNkpYdAdxT8m8VuwElZi7K0wa5y0P0G3ubS8RE7bfMY_mzksdlzwzc_1Hg3QhjOdC_8ULJxx3LNE20kP6gBUmDypOWJfunLh9zFueny_bz84mXbbx46-gDQMwesA1aawCo12tll2hMNi49_H40RbkE1rGC3LO3nBVG7bCTEHcSh4clKcg5_uR6xt9xqjtVC3d-4d0Xq3cmSUIne6tyNL3rbeuObwPBtTN7dBBGmp_BjFyXyX3-ITM1EM-73-tbA7yj4LekDjJMiUluu3HGQ6y5YwffpG92ZQ3Z3KijAKYtLWwy2b0umiUus8clxBqFYe4ncoU8GzzpwB02Ijh-2HNXFY48XGmlomoJGi-GqPLIaVmXGvq63kdu4CGp1bOh7slnk4DOrQRGPvczFOq_yzfNOitBU9Ilf8nx17A4zFGZVd-pgaaOw4NHi-84pSMAACjfgALrkyZMlcBy0LwpfaAKD9de0ESJUJiqxZwuvO07mwGgUjDo0mwC6qFH-O0FCPxLOwr6ijq_qGjriLuXfixKVzs0tzzorPJWbgvZz3w4y969EkunEC0lxxRaD-etvZkMqwuOZScVTmEQrRd0q8_bTHcsi7JgNy9-q4jA6iWwTEMdIb6y37o6OPiZH4yK4Ap0S6h7pSYKy3o2jXZUQJ5oUHYMOZENooICuks49dlpTc11Sn6Lf-2bq3VCAppVhMHdOsWxMmnGSM2XsaF2t_oaO9NbgjPU71kXryL9Va8odE--P8LEpUFoP1HbhDmnEKyV_kMw_IfMzccnUQ-fkJSPBCArO_lJnPmXXz-L5AjaxZ8ncgnlY13jJYuKXIE2s3NHwSMjCcOqqTq9nYBenFQNf5v78kRE5KJmoctr6Utczr3zQMb433TXITHxaRhApKyHhkpWAwO9UhTTBWcryXkgcs9rTFyVbRfFQOmTF4V)

**Comment by fyliu** [comment]
Moving this here to clean up Bonnie's original comment above.

> * does DR (Django-recurrence) replace this issue [Create Table: cancelled_event #57](https://github.com/hackforla/peopledepot/issues/57)
  - In a word, NO. But we can make it work. See the next point.
  - Functionally, we don't need a list of cancelled events that #57 would provide. We really need a list of "all" events, including cancelled ones. DR doesn't come with a way to return all events including cancelled ones. It only does the "smart" thing and return all included events minus all excluded ones. Given it provides so much out of the box (models, managers, wrapper code around dateutil.rrule.rrule and rruleset, etc.), I think we still want to keep it rather than implement our own. The way I see it is we have options to give us the cancelled events we need, with tradeoffs.
    1. add the functionality in DR to return all events with cancellation status. There are sub-options in this and we have flexibility to choose one that best fits our needs. [This is the place](https://github.com/jazzband/django-recurrence/blob/master/recurrence/base.py) to modify.
       1. we can make the default behavior do what we want, which is to return the unfiltered events list with an added field for whether or not each one is cancelled. This is okay since we're the only one using this modified code. It'll break the existing tests because we're modifying the underlying assumptions about the behaviors of that code. On the up side, it's cleaner when we use it. We just call the same interface and it does exactly what we want. We can fix the broken tests too.
       1. we can leave the default behavior that gives us all the non-cancelled events, and add a separate function to give us only the cancelled events. Code-wise, this is cleaner. It leaves the existing code and tests that go along with them. Interface-wise, This is messier, since it adds a little extra work when we use it, since we would need to combine the lists. Ultimately, it's up to how VRMS wants the data. It could be that they also need just the cancelled events for one of their displays.
    1. add an exdate array (list of excluded dates, meaning cancelled events) outside of DR RecurrenceField and don't set the exdate field inside RecurrenceField. This will make DR give us all the event dates and we manually apply the cancelled dates. This is less good since it means having an extra field, but it means we can use the RecurrenceField without modification. It's also less good if we consider the case where we want to use the exrule (recurrence rule that is an exclude, like NOT on the first Wednesdays of the month)
  - We should discuss these options as a team to see what we think of each one. We should also talk to VRMS about what they need from this.

Tasks:
  - [ ] create issue to Implement cancelled events behavior

**Comment by fyliu** [comment]
- [ ] create a "create table" issue for this design.

**Comment by fyliu** [comment]
@Neecolaa and I decided to rename the `recurring_event` table to `event` since that's what the new `event` table is actually doing. I'm adding notes to related issues the should be informed of this redesign.

We need to pause this issue until #173 is done. It will do the rename, but it contains changes that we can make before tackling this one. This is probably the better path even though it's going to change the same model twice.

**Comment by fyliu** [comment]
Since this is an epic issue, we need to 

- [ ] create a work issue to update the `event` model.

**Comment by fyliu** [comment]
I think this needs some more work to create work issues.

**Comment by fyliu** [comment]
I started a thread to compare a new option that showed up recently at
- #420

Their differences are not small, and we'd have to use each in a different way.

**Comment by fyliu** [comment]
Progress update
1. Progress:

    - I started looking at django-recurrence and django-recurring.
    - django-recurring is a new package that claims to solve some long-standing django-recurrence problems. But it's implemented differently as a fork.
    - Neither does what we need out of the box.
    - I need to understand them better to determine if either can be modified/used relatively easily to do what we need.
    - If both require extensive work, then we should just implement our own. Maybe we can use inpiration from these packages.

1. Blockers: It'd be better if I have a clearer set of our Event requirements for evaluating the packages.
1. Availability: M-Th next week
1. ETA: Maybe next week
1. Pictures or links* (if necessary): [Discussion link](https://github.com/hackforla/peopledepot/discussions/420) from above.

**Comment by fyliu** [comment]
Status update:
1. Progress: I didn't make any progress this week
2. Blockers: None. I got the requirements from last week's meeting.
3. Availability: M-Th next week
4. ETA: by next meeting
5. Pictures or links* (if necessary): Same discussion link.

**Comment by shmonks** [comment]
@fyliu I don't know whether your last status update was from before or after last week's team meeting but just in case, here's the usual update request:

Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by fyliu** [comment]
Progress: I haven't been able to work on this the past week. I'll make sure to spend time on this this coming week.
Blockers: None
Availability: M-Th a few hours during the day
ETA: Next week

**Comment by fyliu** [comment]
1. Progress:
    - I got to the point where I see that `recurrence` is the best match for what we want, because it has support for `exrules`.
    - I need to write some code as a proof of concept that we can integrate it.
3. Blockers: None
4. Availability: M-Th a few hours during the day
5. ETA: Next week. I should have some code to implement peopledepot's meeting schedule

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by shmonks** [comment]
Please provide update
1. Progress: "What is the current status of your project? What have you completed and what is left to do?"
2. Blockers: "Difficulties or errors encountered."
3. Availability: "How much time will you have this week to work on this issue?"
4. ETA: "When do you expect this issue to be completed?"
5. Pictures or links* (if necessary): "Add any pictures or links that will help illustrate what you are working on."

* remember to add links to the top of the issue if they are going to be needed again.

**Comment by fyliu** [comment]
I'm removing myself from the issue for now since I haven't been working on it.

**Comment by ExperimentsInHonesty** [comment]
Spend time thinking about what we want to happen when we change the time and date of the event that is recurring

**Comment by fyliu** [comment]
# Events

## Terminology and concepts

This is the more common terminology used "in the industry".

- Event (VRMS recurring_events) model
    - describes events that may repeat
    - An instance or object of this model represents one or a series of occurrences.
- EventOccurrence (VRMS events) model
    - represents single instances of events

### RecurrenceField

This is provided by the `django-recurrence` package and is a custom field to store recurring events. This one field does the job of old tables like `frequency`, `wekdays`, etc.
The field's value is really a **varchar** that holds the following elements, separated by newlines (`\r\n` actually)

- `DTSTART` - datetime when the event starts

- `DTEND` - datetime when the event ends

- `RRULE`

    - Recurrence rule list
    - adds repeating occurrences
    - example: **weekly meetings**

- `RDATE`

    - Recurrence date list
    - adds single occurrences
    - example: **single occurrence event**, or an **additional occurrence** to a repeating one, or a **fully manual series of chosen occurrences** like the onboardings

- `EXRULE`

    - Exception rule list
    - removes repeating occurrences
    - example: **exclude the first meeting of each month** because of Leads meetings

- `EXDATE`

    - Exception date list
    - removes single occurrences
    - example: **cancelled event** or time **change of an occurrence**

`django-recurrence` also comes with

- its own tables for internal use like caching. There's no need to use them.
- UI widgets for visually editing the field
    - This is useful if only as a reference for a frontend to implement
    - It's missing a way to specify `dtstart` and `dtend`, which is required to create or change **events that start and end in the future**

## Structure

- Event can have many EventOccurrences

### Event model

```python
class Event(AbstractBaseModel):
    # RecurrenceField

    # These fields are actually part of the RecurrenceField, but it's not
    # performant to query the values inside the field
    # dtstart = models.DateTimeField()
    # dtend = models.DateTimeField()

    # For the future, given Postgres' ability to query inside JSONB fields, it
    # might be better if we make this a JSONB field which contains dtstart and
    # dtend. we can create a functional B-Tree index on the dtend or until value
    # inside the field to speed up queries
    recurrences = RecurrenceField(null=True, blank=True)

    # Event information
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_time = models.TimeField("Start", null=True, blank=True)
    duration_in_min = models.IntegerField(null=True, blank=True)
    additional_info = models.TextField(blank=True)
    video_conference_url = models.URLField(blank=True)

    # associated project, optional
    project = models.ForeignKey(Project, on_delete=models.CASCADE)

    # associated other models
    location = models.ForeignKey("Location", on_delete=models.DO_NOTHING)
    event_type = models.ForeignKey("EventType", on_delete=models.DO_NOTHING)
    org = models.ForeignKey("Org", on_delete=models.DO_NOTHING)

    must_attend = models.JSONField(default=list)
    should_attend = models.JSONField(default=list)
    could_attend = models.JSONField(default=list)
```

- constraint: require either video_conference_url or location

### EventOccurrence model

```python
class EventOccurrence(AbstractBaseModel):
    # FK to Event
    event = models.ForeignKey("Event", on_delete=models.DO_NOTHING)

    # AI suggests using a JSONB field like this
    # override_fields = {
    #     "name": "changed Event name",
    #     "description": "changed Event description",
    # }

    # Event information
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    start_time = models.TimeField("Start", null=True, blank=True)
    duration_in_min = models.IntegerField(null=True, blank=True)
    additional_info = models.TextField(blank=True)
    video_conference_url = models.URLField(blank=True)

    # associated other models
    location = models.ForeignKey("Location", on_delete=models.DO_NOTHING)
    event_type = models.ForeignKey("EventType", on_delete=models.DO_NOTHING)
    org = models.ForeignKey("Org", on_delete=models.DO_NOTHING)
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING)

    must_attend = models.JSONField(default=list)
    should_attend = models.JSONField(default=list)
    could_attend = models.JSONField(default=list)
```

- event - FK to Event

- overridable fields from Event

    The values are null unless they are overriden in the EventOccurrence.

    AI suggests using a single JSONB field for this.
    The advantage is that an empty JSON object means no override. Looping over the JSON gives us exactly the fields to override.

    - name
    - event_type (FK)
    - location (FK)
    - brigade (FK)
    - video conference url
    - start_time
    - duration_in_min
    - additional_info
    - project
    - must_attend?
    - should_attend?
    - could_attend?

### CancelledEventOccurrence

Event occurrences that are cancelled are moved to the CancelledEventOccurrence table.
This allows us to do various audits to be determined.

Additional field:

- reason - cancellation reason

## Functionality

### What users can do

- Create event
    - Can be recurring or not
    - Create an Event object, along with the initial immediate processing/adding of at least the next few occurrences of it.
- Modify event
    - modify the current event (occurrence)
        - Change the occurrence.
        - If the time is changed, add an EXDATE to the event so it doesn't get generated again.
    - modify the current and future events (occurrences)
        1. Split the event into two. Duplicate the event and set the existing one to end before the new one starts.
            - The new event will point to the old one as an older version of itself.
        1. Delete all the future occurrences of the old event and create new ones for the new event.
            - For the future occurrences with overrides, store them, delete the occurrences, generate the new occurrences, and then apply the overrides to them. This way the overrides will be applied to the new occurrences.
                - There's some cases here like if the event change is to the recurrences or other fields, and whether the overrides are to the occurrence time or other fields.
    - modify all events (occurrences)
        - Do we want to support this, since it means changing the past? Maybe be very clear to the user what this does.
        - Change the event.
        - Do we want to reset any overrides in the occurrences if that field is the change?
- Delete event
    - delete the current event (occurrence)
        - Move it to the DeletedEventOccurrence table with a reason.
        - Add an EXDATE in the event so that it doesn't get added again.
    - delete the current and future events (occurrences)
        - set event end date to now
        - move the future occurrences to the DeletedEventOccurrence table
    - delete the event (flag it as deleted?)
        - do we want to support this, since it means changing the past?
        - delete the event
        - Do we want to delete the past occurrences?
- Create a global exeption date or rule
    - This would be a custom action endpoint


### Event fields

- Event fields are inherited by EventOccurrence objects unless the occurrence overrides them. This saves space and reduces redundancy.

### Event versioning

- Event versions are stored in the Event table.
- An event can have multiple versions, where the current version has the `is_current` flag set, and points to the previous version via the `version_of` field. Each version points to the next version until the end.
- When processing events, the query should take all the current version events and process them first. Then traverse to any unexpired older versions and process them.

### Event management

- **create an event**

    - server process immediately generates `<number>` months' EventOccurrences from the Event
        - so users can do check-ins against them
        - so a client can show them in a calendar view
        - so an admin can manage them (modify and delete)

- **modify the event** by updating some fields

    - this will remove all future occurrences and regenerate them

- **delete the event**

    - this will remove all future occurrences
        - move them to the DeletedEventOccurrence table?

### Occurrence management

- An automated async process triggers server process to generate more EventOccurrences for all non-expired events.

    - this is done at a fixed interval (e.g. run every 1 month to generate 2 months into the future)
    - there needs to be a timestamp for when processing is last complete, for each event maybe good enough
        - this is for VRMS troubleshooting purposes
    - remove EventOccurrences that are in the past but nobody checked into (to save space?)
        An admin can manage the generated EventOccurrences for an Event.

If an occurrence is in the future, the admin can:

- **modify the occurrence** by updating some fields
    - this will populate the override fields that modify what's in the Event
    - special case of **modifying the time**:
        - this will also add an EXDATE in the Event.recurrances RRULESet
            - so that the serve process will not generate it again
- **delete the occurrence**
    - this will move the occurrence to the DeletedEventOccurrence table
        - to mark it as deleted
    - this will add an EXDATE in the Event.recurrances RRULESet
        - so that the serve process will not generate it again

## Requirements

These are the use cases that need to be supported. The descriptions of these should really be moved to the implementation above if not already.

- Exclude holiday for all meetings for all teams
    - Can create a custom endpoint for this case.
        - The server can process all the current events and add the exclusion EXDATE to each one.
        - Move the occurrences to the DeletedEventOccurrence table with the reason.
        - Add team exclusions to the endpoint params or move the occurrences back.
        - The drawback is it doesn't leave a data trail of the exclusion action for auditing. We might need to revisit this later.
- Change the time of 1 meeting to start 15 minutes later.
    - See "modify the current event (occurrence)", and the special case of "modifying the time" above.
- Change the time (or other detail) of a meeting permanently and update future occurrences.
    - See "modify the current and future events (occurrences)" above.
- Cancel a single meeting
    - See "delete the current event (occurrence)" above.
- Change an event in the future
    - See "modify the current and future events (occurrences)" above for a very similar case.
    - This is a special case, or rather the more generic case, where the event is split with a future `dtstart` for the new version.
    - The `django-recurrence` widget doesn't support setting the dtstart and dtend. This means we either can't perform this action in django admin or we need to add it outselves.
- Check for conflict where event name is the same but time overlaps
    - this should be done when creating or updating the event, so th ebackend can return an error and the frontend can notify the user to confirm the action
- VRMS requirements
    - will poll events for next 24 hours
    - will poll after VRMS initiates an event change
    - exclude a date -> ask for a reason -> extra reason field for cancelled event
    - need timestamps of when events processing happens
        - for troubleshooting
        - last time the events objects were generated - per event it seems like

## Other notes

- We might need to move the attendance fields to real tables if we need to do queries on them
    - looks like postgres json fields are queryable, especially the jsonb fields
    - looks like event joins between jsonb fields and real tables are possible
    - we need to figure out what queries we need to support

**Comment by ExperimentsInHonesty** [comment]
add last generated field to event table

**Comment by ExperimentsInHonesty** [comment]
If we are trying to make it so that the event occurrences can be regenerated at any time, the reason for a cancelation has to be stored in a history table

Table: Event Cancelation History
event (ID) | event_date | canceled_at | reason | canceled_by
-- | -- | -- | -- | --
8787 | 2026-02-14 | 2026-01-29 | holiday | 8888

**Comment by fyliu** [comment]
@ExperimentsInHonesty @Neecolaa 
We should rename the Event table field `rrule` to `recurrences` because it can contain other things such as exrules. 
- https://github.com/hackforla/peopledepot/issues/88#issuecomment-3560711985

**Comment by ExperimentsInHonesty** [comment]
@fyliu - Nicole and I understand the "previous_version" field in the event table (i.e., it tells you if the event was significatly different than before and this event permanently replaces it).  

We also the "previous_version" table in the eventoccurrance table and that table also has event which points to the uuid of the event in the event table.  

Do we still need the "previous_version" field in the event occurance table, or can we delete it?

**Comment by ExperimentsInHonesty** [comment]
@Neecolaa Spoke to Fang on 2026-09-03 and we agree we don't need "previous_version"in the eventoccurance table.  I have removed it from the sheet [PD: Table and field explanations, current Field Permissions](https://docs.google.com/spreadsheets/d/1x_zZ8JLS2hO-zG0jUocOJmX16jh-DF5dccrd_OEGNZ0/edit?gid=749942651#gid=749942651).  

- Remove "previous_version" from the  eventoccurance table.

**Comment by fyliu** [comment]
I'm working on writing out the event design in the wiki to cover all the models and all the concerns we had. https://github.com/hackforla/peopledepot/wiki/Events

I was looking at the CancelledEvent issue and checked some thoughts against an LLM to see if it agreed and it returned different suggestions.

Several LLM suggestions:
1. **"canceled" vs. "cancelled"**.

	Is there a preference? The single-l is the American spelling and is the one being used in the software industry.

1. `CancelledEvent`
	1. Combine `CancelledEvent` table into `EventOccurrence`

		It's better to include the `CancelledEvent` fields in `EventOccurrence` since the disk space waste is negligible due to a **Null Bitmap feature** in PostgreSQL that stores blank values efficiently. The extra logic to work with a separate table is a more significant performance cost.

		Actually, it would be **stored in `EventOccurrenceChange`** since it's where we store custom data for event instances. But for query efficiency (not having to join), we could add a `status` field in `EventOccurrence` that's set from `EventOccurrenceChange` during the re-linking step.

	1. **Don't store cancellations in `rrules`** - We talked about storing the cancellations in the `rrules`. But if we need to set the auditing data (cancelled_by, reason, cancelled on), we should just not use `rrules` to "not generate occurrences", and then have to keep the cancelled occurrences in a separate table using a custom workflow.

1. Archiving old events

	PostgreSQL has a **partitioning feature** where we can tell it to store each year's data in a separate partition without creating a new `OldEventOccurence` table and manually moving rows over. The partitions are actually separate tables that exist as separate files but work transparently as one. We take advantage of the feature by adding a datetime to queries so the database will limit the search to the relevant partitions only.

	We could create a management command to create a new partition for the next year and run it ahead of when we'll need to store into it. This is assuming a year's data is going to be fast to query through. The original intent for archiving old events is so that querying recent events, which we mainly care about, will be fast, and there will be a time when parsing old data will slow down queries.
